
export const ENV_CONFIG = {
  VITE_SUPABASE_URL: "",
  VITE_SUPABASE_ANON_KEY: "",
  VITE_GEMINI_API_KEY: "",
  VITE_SARVAM_API_KEY: "",
  VITE_COLLAB_SERVER_URL: "",
  VITE_GROK_API_KEY: "",
  VITE_GROQ_API_KEY: "",
  VITE_INTERVIEW_API_KEY: ""
};
