-- Seed data for problems table

INSERT INTO problems (title, slug, difficulty, tags, acceptance_rate, companies, platform, description, examples, constraints) VALUES
(
  'Two Sum',
  'two-sum',
  'easy',
  '{"array","hash-table"}',
  49.2,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.',
  '[{"input":"[2,7,11,15], 9","output":"[0,1]","explanation":"Because nums[0] + nums[1] == 9, we return [0, 1]."}]'::jsonb,
  '{"2 <= nums.length <= 10^4","-10^9 <= nums[i] <= 10^9","Only one valid answer exists."}'
),
(
  'Longest Substring Without Repeating Characters',
  'longest-substring-without-repeating-characters',
  'medium',
  '{"string","sliding-window"}',
  31.4,
  '{"Facebook","Amazon","Apple"}',
  'leetcode',
  'Given a string s, find the length of the longest substring without repeating characters.',
  '[{"input":"abcabcbb","output":"3","explanation":"The answer is \"abc\", with the length of 3."},{"input":"bbbbb","output":"1","explanation":"The answer is \"b\", with the length of 1."}]'::jsonb,
  '{"0 <= s.length <= 5 * 10^4","s consists of only lowercase English letters."}'
),
(
  'Median of Two Sorted Arrays',
  'median-of-two-sorted-arrays',
  'hard',
  '{"array","binary-search","divide-and-conquer"}',
  35.8,
  '{"Google","Microsoft","Facebook"}',
  'leetcode',
  'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.',
  '[{"input":"[1,3], [2]","output":"2.00000","explanation":"The merged array is [1,2,3] and the median is 2.0."},{"input":"[1,2], [3,4]","output":"2.50000","explanation":"The merged array is [1,2,3,4] and the median is (2 + 3) / 2 = 2.5."}]'::jsonb,
  '{"nums1.length == m","nums2.length == n","0 <= m, n <= 1000","-10^6 <= nums1[i], nums2[i] <= 10^6"}'
),
(
  'Longest Palindromic Substring',
  'longest-palindromic-substring',
  'medium',
  '{"string","dynamic-programming"}',
  33.1,
  '{"Amazon","Microsoft","Oracle"}',
  'leetcode',
  'Given a string s, return the longest palindromic substring in s.',
  '[{"input":"babad","output":"bab","explanation":"The answer is \"bab\", with the length of 3."},{"input":"cbbd","output":"bb","explanation":"The answer is \"bb\", with the length of 2."}]'::jsonb,
  '{"1 <= s.length <= 1000","s consists of only lowercase English letters and digits."}'
),
(
  'Reverse Integer',
  'reverse-integer',
  'medium',
  '{"math"}',
  26.8,
  '{"Apple","Google","Adobe"}',
  'leetcode',
  'Given a signed 32-bit integer x, return x with its digits reversed.',
  '[{"input":"123","output":"321","explanation":"Reversing 123 gives 321."},{"input":"-123","output":"-321","explanation":"Reversing -123 gives -321."},{"input":"120","output":"21","explanation":"Reversing 120 gives 21."}]'::jsonb,
  '{"-2^31 <= x <= 2^31 - 1","x is a 32-bit signed integer"}'
),
(
  'String to Integer (atoi)',
  'string-to-integer-atoi',
  'medium',
  '{"string","math"}',
  16.3,
  '{"Microsoft","Amazon","Facebook"}',
  'leetcode',
  'Implement the myAtoi function which converts a string to a 32-bit signed integer.',
  '[{"input":"42","output":"42","explanation":"The string \"42\" is converted to integer 42."},{"input":"   -42","output":"-42","explanation":"Leading spaces are ignored."},{"input":"4193 with words","output":"4193","explanation":"Conversion stops when encountering non-digit characters."}]'::jsonb,
  '{"0 <= s.length <= 200","s consists of digits, optional sign, letters, and spaces."}'
),
(
  'Palindrome Number',
  'palindrome-number',
  'easy',
  '{"math"}',
  55.7,
  '{"Google","Apple","Microsoft"}',
  'leetcode',
  'Given an integer x, return true if x is a palindrome, and false otherwise.',
  '[{"input":"121","output":"true","explanation":"121 reads as 121 backward."},{"input":"-121","output":"false","explanation":"-121 reads as -121 backward."},{"input":"10","output":"false","explanation":"10 reads as 01 backward."}]'::jsonb,
  '{"-2^31 <= x <= 2^31 - 1","x is a 32-bit signed integer"}'
),
(
  'Regular Expression Matching',
  'regular-expression-matching',
  'hard',
  '{"string","dynamic-programming","recursion"}',
  27.1,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given an input string s and a pattern p, return true if the pattern matches the entire string s.',
  '[{"input":"aa, p: a","output":"false","explanation":"The pattern \"a\" does not match the entire string \"aa\"."},{"input":"mississippi, p: s","output":"false","explanation":"The pattern \"s\" does not match the entire string \"mississippi\"."}]'::jsonb,
  '{"0 <= s.length <= 20","p contains only lowercase English letters."}'
),
(
  'Container With Most Water',
  'container-with-most-water',
  'medium',
  '{"array","two-pointers"}',
  51.3,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given n non-negative integers a1, a2, ..., an, where each represents a vertical line at coordinate x = i.',
  '[{"input":"[1,8,6,2,5,4,7,8,3,7]","output":"49","explanation":"The container holds 49 units of water."},{"input":"[1,1,1,2,1]","output":"7","explanation":"The container holds 7 units of water."}]'::jsonb,
  '{"1 <= n <= 10^5","0 <= ai <= 10^4","ai is the height of the ith line."}'
),
(
  'Roman to Integer',
  'roman-to-integer',
  'easy',
  '{"string","math"}',
  56.4,
  '{"Google","Facebook","Oracle"}',
  'leetcode',
  'Given a roman numeral, convert it to an integer.',
  '[{"input":"III","output":"3","explanation":"III converts to 3."},{"input":"IV","output":"4","explanation":"IV converts to 4."},{"input":"IX","output":"9","explanation":"IX converts to 9."},{"input":"LVIII","output":"58","explanation":"LVIII converts to 58."},{"input":"MCMXCIV","output":"1994","explanation":"MCMXCIV converts to 1994."}]'::jsonb,
  '{"1 <= s.length <= 15","s contains only the characters I, V, X, L, C, D, and M."}'
),
(
  'Longest Common Prefix',
  'longest-common-prefix',
  'easy',
  '{"string"}',
  36.2,
  '{"Amazon","Microsoft","Apple"}',
  'leetcode',
  'Write a function to find the longest common prefix string amongst an array of strings.',
  '[{"input":"[\"flower\",\"flow\",\"flight\"]","output":"\"fl\"","explanation":"The longest common prefix is \"fl\"."},{"input":"[\"dog\",\"racecar\",\"car\"]","output":"\"\"","explanation":"There is no common prefix among the input strings."}]'::jsonb,
  '{"1 <= strs.length <= 200","0 <= strs[i].length <= 200"}'
),
(
  '3Sum',
  '3sum',
  'medium',
  '{"array","two-pointers"}',
  28.5,
  '{"Google","Facebook","Amazon"}',
  'leetcode',
  'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.',
  '[{"input":"[-1,0,1,2,-1,-4]","output":"[[-1,-1,2],[-1,0,1]]","explanation":"The solution set contains unique triplets that sum to zero."},{"input":"[0,0,0,0]","output":"[[0,0,0]]","explanation":"The only triplet that sums to zero is [0,0,0]."}]'::jsonb,
  '{"0 <= nums.length <= 3000","-10^5 <= nums[i] <= 10^5"}'
),
(
  'Letter Combinations of a Phone Number',
  'letter-combinations-of-a-phone-number',
  'medium',
  '{"string","backtracking"}',
  47.8,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent.',
  '[{"input":"\"23\"","output":"[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]","explanation":"All possible combinations for digits 2 and 3."},{"input":"\"\"","output":"[]","explanation":"Empty input returns empty array."},{"input":"\"2\"","output":"[\"a\",\"b\",\"c\"]","explanation":"Digit 2 maps to letters a, b, c."}]'::jsonb,
  '{"0 <= digits.length <= 10","digits consists of only digits 2-9."}'
),
(
  'Valid Parentheses',
  'valid-parentheses',
  'easy',
  '{"string","stack"}',
  40.1,
  '{"Facebook","Amazon","Google"}',
  'leetcode',
  'Given a string s containing just the characters ''('', '')'', ''{'', ''}'', ''['' and '']'', determine if the input string is valid.',
  '[{"input":"\"()\"","output":"true","explanation":"The parentheses are properly closed."},{"input":"\"()[]{}\"","output":"true","explanation":"All brackets are properly closed in the correct order."},{"input":"\"(]\"","output":"false","explanation":"The closing bracket does not match the opening bracket."}]'::jsonb,
  '{"1 <= s.length <= 10^4","s consists of only parentheses, brackets, and braces."}'
),
(
  'Merge Two Sorted Lists',
  'merge-two-sorted-lists',
  'easy',
  '{"linked-list","recursion"}',
  58.3,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Merge two sorted linked lists and return it as a sorted list. The list should be made by splicing together the nodes of the first two lists.',
  '[{"input":"[1,2,4], [1,3,4]","output":"[1,1,2,3,4,4]","explanation":"The merged list combines both lists in sorted order."},{"input":"[], []","output":"[]","explanation":"Both empty lists result in an empty list."},{"input":"[], [0]","output":"[0]","explanation":"Empty list merged with [0] results in [0]."}]'::jsonb,
  '{"The number of nodes in both lists is in the range [0, 50].","-100 <= Node.val <= 100","Both lists are sorted in non-decreasing order."}'
),
(
  'Generate Parentheses',
  'generate-parentheses',
  'medium',
  '{"string","backtracking"}',
  71.3,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.',
  '[{"input":"n = 3","output":"[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]","explanation":"All valid combinations of 3 pairs of parentheses."},{"input":"n = 1","output":"[\"()\"]","explanation":"Only one valid combination for 1 pair."}]'::jsonb,
  '{"1 <= n <= 8","n is a positive integer."}'
),
(
  'Merge k Sorted Lists',
  'merge-k-sorted-lists',
  'hard',
  '{"linked-list","divide-and-conquer","heap"}',
  42.6,
  '{"Google","Facebook","Amazon"}',
  'leetcode',
  'Given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.',
  '[{"input":"[[1,4,5],[1,3,4],[2,6]]","output":"[1,1,2,3,4,4,5,6]","explanation":"All lists merged into one sorted list."},{"input":"[]","output":"[]","explanation":"Empty input results in empty list."},{"input":"[[]]","output":"[]","explanation":"List containing empty list results in empty list."}]'::jsonb,
  '{"k == lists.length","0 <= k <= 10^4","0 <= lists[i].length <= 500","-10^4 <= lists[i][j] <= 10^4"}'
),
(
  'Swap Nodes in Pairs',
  'swap-nodes-in-pairs',
  'medium',
  '{"linked-list","recursion"}',
  56.8,
  '{"Microsoft","Amazon","Google"}',
  'leetcode',
  'Given a linked list, swap every two adjacent nodes and return its head.',
  '[{"input":"[1,2,3,4]","output":"[2,1,4,3]","explanation":"Nodes 1-2 and 3-4 are swapped."},{"input":"[]","output":"[]","explanation":"Empty list remains empty."},{"input":"[1]","output":"[1]","explanation":"Single node remains unchanged."}]'::jsonb,
  '{"The number of nodes in the list is in the range [0, 100].","0 <= Node.val <= 100"}'
),
(
  'Reverse Nodes in k-Group',
  'reverse-nodes-in-k-group',
  'hard',
  '{"linked-list","recursion"}',
  44.9,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given the head of a linked list, reverse the nodes of the list k at a time, and return the modified list.',
  '[{"input":"[1,2,3,4,5], k = 2","output":"[2,1,4,3,5]","explanation":"First 2 nodes reversed, then next 2 nodes, last node remains."},{"input":"[1,2,3,4,5], k = 3","output":"[3,2,1,4,5]","explanation":"First 3 nodes reversed, last 2 nodes remain as is."}]'::jsonb,
  '{"The number of nodes in the list is in the range [1, 5000].","0 <= Node.val <= 5000","1 <= k <= length of the linked list"}'
),
(
  'Remove Duplicates from Sorted Array',
  'remove-duplicates-from-sorted-array',
  'easy',
  '{"array","two-pointers"}',
  49.7,
  '{"Amazon","Microsoft","Apple"}',
  'leetcode',
  'Given an integer array nums sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once.',
  '[{"input":"[1,1,2]","output":"2, nums = [1,2,_]","explanation":"Array becomes [1,2] with length 2."},{"input":"[0,0,1,1,1,2,2,3,3,4]","output":"5, nums = [0,1,2,3,4,_,_,_,_,_]","explanation":"Array becomes [0,1,2,3,4] with length 5."}]'::jsonb,
  '{"1 <= nums.length <= 3 * 10^4","-10^4 <= nums[i] <= 10^4","nums is sorted in non-decreasing order."}'
),
(
  'Remove Element',
  'remove-element',
  'easy',
  '{"array","two-pointers"}',
  49.4,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given an integer array nums and an integer val, remove all occurrences of val in nums in-place.',
  '[{"input":"[3,2,2,3], val = 3","output":"2, nums = [2,2,_,_]","explanation":"Array becomes [2,2] with length 2."},{"input":"[0,1,2,2,3,0,4,2], val = 2","output":"5, nums = [0,1,4,0,3,_,_,_]","explanation":"Array becomes [0,1,4,0,3] with length 5."}]'::jsonb,
  '{"0 <= nums.length <= 100","0 <= nums[i] <= 50","0 <= val <= 100"}'
),
(
  'Implement strStr()',
  'implement-strstr',
  'easy',
  '{"string","two-pointers"}',
  36.2,
  '{"Microsoft","Amazon","Google"}',
  'leetcode',
  'Return the index of the first occurrence of needle in haystack, or -1 if needle is not part of haystack.',
  '[{"input":"haystack = \"hello\", needle = \"ll\"","output":"2","explanation":"The first occurrence of \"ll\" in \"hello\" is at index 2."},{"input":"haystack = \"aaaaa\", needle = \"bba\"","output":"-1","explanation":"\"bba\" does not occur in \"aaaaa\"."}]'::jsonb,
  '{"1 <= haystack.length, needle.length <= 10^4","haystack and needle consist of only lowercase English characters."}'
),
(
  'Search Insert Position',
  'search-insert-position',
  'easy',
  '{"array","binary-search"}',
  43.7,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a sorted array of distinct integers and a target value, return the index if the target is found.',
  '[{"input":"[1,3,5,6], target = 5","output":"2","explanation":"Target 5 is found at index 2."},{"input":"[1,3,5,6], target = 2","output":"1","explanation":"Target 2 would be inserted at index 1."},{"input":"[1,3,5,6], target = 7","output":"4","explanation":"Target 7 would be inserted at index 4."}]'::jsonb,
  '{"1 <= nums.length <= 10^4","-10^4 <= nums[i] <= 10^4","nums contains distinct values sorted in ascending order."}'
),
(
  'Maximum Subarray',
  'maximum-subarray',
  'medium',
  '{"array","divide-and-conquer","dynamic-programming"}',
  48.9,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'Given an integer array nums, find the contiguous subarray with the largest sum and return its sum.',
  '[{"input":"[-2,1,-3,4,-1,2,1,-5,4]","output":"6","explanation":"The subarray [4,-1,2,1] has the largest sum 6."},{"input":"[1]","output":"1","explanation":"The subarray [1] has the largest sum 1."},{"input":"[5,4,-1,7,8]","output":"23","explanation":"The subarray [5,4,-1,7,8] has the largest sum 23."}]'::jsonb,
  '{"1 <= nums.length <= 10^5","-10^4 <= nums[i] <= 10^4"}'
),
(
  'Length of Last Word',
  'length-of-last-word',
  'easy',
  '{"string"}',
  40.1,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a string s consisting of words and spaces, return the length of the last word in the string.',
  '[{"input":"\"Hello World\"","output":"5","explanation":"The last word is \"World\" with length 5."},{"input":"\"   fly me   to   the moon  \"","output":"4","explanation":"The last word is \"moon\" with length 4."},{"input":"\"luffy is still joyboy\"","output":"6","explanation":"The last word is \"joyboy\" with length 6."}]'::jsonb,
  '{"1 <= s.length <= 10^4","s consists of only English letters and spaces."}'
),
(
  'Plus One',
  'plus-one',
  'easy',
  '{"array","math"}',
  44.2,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer.',
  '[{"input":"[1,2,3]","output":"[1,2,4]","explanation":"The array represents the integer 123, incrementing gives 124."},{"input":"[4,3,2,1]","output":"[4,3,2,2]","explanation":"The array represents 4321, incrementing gives 4322."},{"input":"[9]","output":"[1,0]","explanation":"The array represents 9, incrementing gives 10."}]'::jsonb,
  '{"1 <= digits.length <= 100","0 <= digits[i] <= 9","digits does not contain any leading 0."}'
),
(
  'Add Binary',
  'add-binary',
  'easy',
  '{"string","math","bit-manipulation"}',
  45.3,
  '{"Microsoft","Amazon","Google"}',
  'leetcode',
  'Given two binary strings a and b, return their sum as a binary string.',
  '[{"input":"a = \"11\", b = \"1\"","output":"\"100\"","explanation":"11 (3) + 1 (1) = 100 (4) in binary."},{"input":"a = \"1010\", b = \"1011\"","output":"\"10101\"","explanation":"1010 (10) + 1011 (11) = 10101 (21) in binary."}]'::jsonb,
  '{"1 <= a.length, b.length <= 10^4","a and b consist only of characters ''0'' or ''1''.","Each string does not contain leading zeros except for the zero itself."}'
),
(
  'Sqrt(x)',
  'sqrtx',
  'easy',
  '{"math","binary-search"}',
  38.7,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a non-negative integer x, return the square root of x rounded down to the nearest integer.',
  '[{"input":"x = 4","output":"2","explanation":"The square root of 4 is 2."},{"input":"x = 8","output":"2","explanation":"The square root of 8 is 2.828..., rounded down is 2."}]'::jsonb,
  '{"0 <= x <= 2^31 - 1"}'
),
(
  'Climbing Stairs',
  'climbing-stairs',
  'easy',
  '{"math","dynamic-programming","memoization"}',
  51.2,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps.',
  '[{"input":"n = 2","output":"2","explanation":"There are two ways to climb to the top: 1 step + 1 step, or 2 steps."},{"input":"n = 3","output":"3","explanation":"There are three ways to climb to the top: 1+1+1, 1+2, or 2+1."}]'::jsonb,
  '{"1 <= n <= 45"}'
),
(
  'Remove Duplicates from Sorted List',
  'remove-duplicates-from-sorted-list',
  'easy',
  '{"linked-list"}',
  47.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given the head of a sorted linked list, delete all duplicates such that each element appears only once.',
  '[{"input":"[1,1,2]","output":"[1,2]","explanation":"The duplicate 1 is removed, leaving [1,2]."},{"input":"[1,1,2,3,3]","output":"[1,2,3]","explanation":"Duplicates 1 and 3 are removed, leaving [1,2,3]."}]'::jsonb,
  '{"The number of nodes in the list is in the range [0, 300].","-100 <= Node.val <= 100","The list is guaranteed to be sorted in ascending order."}'
),
(
  'Two Sum II - Input array is sorted',
  'two-sum-ii-input-array-is-sorted',
  'medium',
  '{"array","two-pointers"}',
  58.1,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given a 1-indexed array of integers numbers that is already sorted in non-decreasing order, find two numbers such that they add up to a specific target number.',
  '[{"input":"[2,7,11,15], target = 9","output":"[1,2]","explanation":"The sum of elements at indices 1 and 2 is 9."},{"input":"[2,3,4], target = 6","output":"[1,3]","explanation":"The sum of elements at indices 1 and 3 is 6."}]'::jsonb,
  '{"2 <= numbers.length <= 3 * 10^4","-1000 <= numbers[i] <= 1000","numbers is sorted in non-decreasing order."}'
),
(
  'Trapping Rain Water',
  'trapping-rain-water',
  'hard',
  '{"array","two-pointers","stack","dynamic-programming"}',
  56.7,
  '{"Google","Amazon","Microsoft"}',
  'leetcode',
  'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
  '[{"input":"[0,1,0,2,1,0,1,3,2,1,2,1]","output":"6","explanation":"6 units of water can be trapped."},{"input":"[4,2,0,3,2,5]","output":"9","explanation":"9 units of water can be trapped."}]'::jsonb,
  '{"n == height.length","1 <= n <= 2 * 10^4","0 <= height[i] <= 10^5"}'
),
(
  'Permutations',
  'permutations',
  'medium',
  '{"array","backtracking"}',
  68.3,
  '{"Facebook","Amazon","Google"}',
  'leetcode',
  'Given an array nums of distinct integers, return all possible permutations.',
  '[{"input":"[1,2,3]","output":"[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]","explanation":"All possible permutations of [1,2,3]."},{"input":"[0,1]","output":"[[0,1],[1,0]]","explanation":"All possible permutations of [0,1]."}]'::jsonb,
  '{"1 <= nums.length <= 6","-10 <= nums[i] <= 10","All elements of nums are unique."}'
),
(
  'Rotate Image',
  'rotate-image',
  'medium',
  '{"array","math","matrix"}',
  61.2,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'You are given an n x n 2D matrix representing an image, rotate the image by 90 degrees (clockwise).',
  '[{"input":"[[1,2,3],[4,5,6],[7,8,9]]","output":"[[7,4,1],[8,5,2],[9,6,3]]","explanation":"Matrix rotated 90 degrees clockwise."},{"input":"[[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]","output":"[[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]]","explanation":"4x4 matrix rotated 90 degrees clockwise."}]'::jsonb,
  '{"n == matrix.length","n == matrix[i].length","1 <= n <= 20","-1000 <= matrix[i][j] <= 1000"}'
),
(
  'Group Anagrams',
  'group-anagrams',
  'medium',
  '{"array","hash-table","string","sorting"}',
  62.9,
  '{"Amazon","Google","Facebook"}',
  'leetcode',
  'Given an array of strings strs, group the anagrams together.',
  '[{"input":"[\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]","output":"[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]","explanation":"Groups of anagrams based on sorted characters."},{"input":"[\"\"]","output":"[[\"\"]]","explanation":"Single string forms its own group."}]'::jsonb,
  '{"1 <= strs.length <= 10^4","0 <= strs[i].length <= 100","strs[i] consists of lowercase English letters."}'
),
(
  'Maximum Product Subarray',
  'maximum-product-subarray',
  'medium',
  '{"array","dynamic-programming"}',
  34.2,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'Given an integer array nums, find a contiguous subarray that has the largest product, and return the product.',
  '[{"input":"[2,3,-2,4]","output":"6","explanation":"The subarray [2,3] has the largest product 6."},{"input":"[-2,0,-1]","output":"0","explanation":"The result cannot be 2, because [-2,-1] is not a subarray."}]'::jsonb,
  '{"1 <= nums.length <= 2 * 10^4","-10 <= nums[i] <= 10","The product of any prefix or suffix of nums is guaranteed to fit in a 32-bit integer."}'
),
(
  'Word Search',
  'word-search',
  'medium',
  '{"array","backtracking","matrix"}',
  36.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given an m x n board and a word, find if the word exists in the grid.',
  '[{"input":"board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"","output":"true","explanation":"The word exists in the grid."},{"input":"board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"SEE\"","output":"true","explanation":"The word exists in the grid."}]'::jsonb,
  '{"m == board.length","n == board[i].length","1 <= m, n <= 6","1 <= word.length <= 15"}'
),
(
  'Combination Sum',
  'combination-sum',
  'medium',
  '{"array","backtracking"}',
  54.7,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations where the chosen numbers sum to target.',
  '[{"input":"candidates = [2,3,6,7], target = 7","output":"[[2,2,3],[7]]","explanation":"2 and 3 are candidates, 2 + 2 + 3 = 7 and 7 = 7."},{"input":"candidates = [2,3,5], target = 8","output":"[[2,2,2,2],[2,3,3],[3,5]]","explanation":"All combinations that sum to 8."}]'::jsonb,
  '{"1 <= candidates.length <= 30","1 <= candidates[i] <= 200","All elements of candidates are distinct.","1 <= target <= 500"}'
),
(
  'First Missing Positive',
  'first-missing-positive',
  'hard',
  '{"array","hash-table"}',
  34.1,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given an unsorted integer array nums, return the smallest missing positive integer.',
  '[{"input":"[1,2,0]","output":"3","explanation":"The smallest missing positive is 3."},{"input":"[3,4,-1,1]","output":"2","explanation":"The smallest missing positive is 2."},{"input":"[7,8,9,11,12]","output":"1","explanation":"The smallest missing positive is 1."}]'::jsonb,
  '{"1 <= nums.length <= 10^5","-10^9 <= nums[i] <= 10^9"}'
),
(
  'Spiral Matrix',
  'spiral-matrix',
  'medium',
  '{"array","matrix","simulation"}',
  41.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given an m x n matrix, return all elements of the matrix in spiral order.',
  '[{"input":"[[1,2,3],[4,5,6],[7,8,9]]","output":"[1,2,3,6,9,8,7,4,5]","explanation":"Elements visited in spiral order."},{"input":"[[1,2,3,4],[5,6,7,8],[9,10,11,12]]","output":"[1,2,3,4,8,12,11,10,9,5,6,7]","explanation":"Elements visited in spiral order."}]'::jsonb,
  '{"m == matrix.length","n == matrix[i].length","1 <= m, n <= 10","-100 <= matrix[i][j] <= 100"}'
),
(
  'Chef and Ice Cream',
  'chef-and-ice-cream',
  'easy',
  '{"math","implementation"}',
  67.3,
  '{""}',
  'codechef',
  'Chef wants to buy ice cream for his friends. Each ice cream costs X rupees. Chef has Y rupees. Find the maximum number of ice creams Chef can buy.',
  '[{"input":"X = 5, Y = 16","output":"3","explanation":"Chef can buy 3 ice creams with 16 rupees."},{"input":"X = 3, Y = 9","output":"3","explanation":"Chef can buy 3 ice creams with 9 rupees."}]'::jsonb,
  '{"1 <= X, Y <= 1000"}'
),
(
  'Smallest KMP',
  'smallest-kmp',
  'medium',
  '{"string","pattern-matching"}',
  45.2,
  '{""}',
  'codeforces',
  'You are given a string s consisting of lowercase Latin letters. Find the lexicographically smallest string t such that s occurs as a substring of t (i.e., t contains s as a consecutive block).',
  '[{"input":"s = \"ababa\"","output":"\"ababa\"","explanation":"The string itself is already the smallest."},{"input":"s = \"zzz\"","output":"\"zzz\"","explanation":"The string itself is the smallest possible."}]'::jsonb,
  '{"1 <= |s| <= 10^5","s consists of lowercase Latin letters."}'
),
(
  'Two Teams Composing',
  'two-teams-composing',
  'medium',
  '{"array","math","greedy"}',
  52.8,
  '{""}',
  'codeforces',
  'You have n students, each with a skill level. You need to form two teams: one with all students having the same skill level, and another with all remaining students.',
  '[{"input":"[1,2,2,3]","output":"2","explanation":"Team 1: [2,2], Team 2: [1,3]."},{"input":"[1,1,1,1]","output":"0","explanation":"Cannot form two teams with different skill levels."}]'::jsonb,
  '{"1 <= n <= 100","1 <= ai <= 100"}'
),
(
  'Maximum Sum of Hourglass',
  'maximum-sum-of-hourglass',
  'medium',
  '{"matrix","array"}',
  58.9,
  '{""}',
  'gfg',
  'Given a matrix, find the maximum sum of hourglass in the matrix. An hourglass is defined as a pattern of 7 elements.',
  '[{"input":"[[1,2,3,0,0],[0,0,0,0,0],[2,1,4,0,0],[0,0,0,0,0],[1,1,0,0,0]]","output":"13","explanation":"Hourglass with elements 1,2,3,2,1,4,0 has sum 13."}]'::jsonb,
  '{"1 <= N, M <= 100","-100 <= matrix[i][j] <= 100"}'
),
(
  'Reverse an Array',
  'reverse-an-array',
  'easy',
  '{"array"}',
  78.4,
  '{""}',
  'gfg',
  'Given an array of N integers, write a function to reverse the array.',
  '[{"input":"[1, 2, 3, 4, 5]","output":"[5, 4, 3, 2, 1]","explanation":"Array reversed completely."},{"input":"[10, 20, 30]","output":"[30, 20, 10]","explanation":"Array reversed completely."}]'::jsonb,
  '{"1 <= N <= 10^5","1 <= arr[i] <= 10^9"}'
),
(
  'Find the Median',
  'find-the-median',
  'easy',
  '{"array","sorting"}',
  65.7,
  '{""}',
  'hackerrank',
  'Given an array of integers, find the median of the array.',
  '[{"input":"[0, 1, 2, 3, 4]","output":"2","explanation":"Middle element of sorted array is 2."},{"input":"[7, 13, 5, 1, 3]","output":"5","explanation":"Sorted array is [1,3,5,7,13], median is 5."}]'::jsonb,
  '{"1 <= n <= 10^5","1 <= arr[i] <= 10^9"}'
),
(
  'Anagram',
  'anagram',
  'easy',
  '{"string","hash-table"}',
  71.2,
  '{""}',
  'hackerrank',
  'Given two strings, check if they are anagrams of each other.',
  '[{"input":"\"cde\", \"abc\"","output":"\"Not Anagrams\"","explanation":"Different character frequencies."},{"input":"\"anagram\", \"margana\"","output":"\"Anagrams\"","explanation":"Same character frequencies."}]'::jsonb,
  '{"1 <= len(s), len(t) <= 10^5","Strings contain only lowercase letters."}'
),
(
  'CodeForge Array Rotation',
  'codeforge-array-rotation',
  'easy',
  '{"array"}',
  82.1,
  '{""}',
  'codeforge',
  'Rotate an array to the right by k steps, where k is non-negative.',
  '[{"input":"[1,2,3,4,5,6,7], k = 3","output":"[5,6,7,1,2,3,4]","explanation":"Array rotated right by 3 positions."},{"input":"[-1,-100,3,99], k = 2","output":"[3,99,-1,-100]","explanation":"Array rotated right by 2 positions."}]'::jsonb,
  '{"1 <= nums.length <= 2 * 10^4","-2^31 <= nums[i] <= 2^31 - 1","0 <= k <= 10^5"}'
),
(
  'CodeForge String Palindrome',
  'codeforge-string-palindrome',
  'medium',
  '{"string","two-pointers"}',
  68.9,
  '{""}',
  'codeforge',
  'Given a string, determine if it reads the same backward as forward, ignoring spaces and punctuation.',
  '[{"input":"\"A man, a plan, a canal: Panama\"","output":"true","explanation":"String is a palindrome when ignoring non-alphanumeric characters."},{"input":"\"race a car\"","output":"false","explanation":"String is not a palindrome even after ignoring non-alphanumeric characters."}]'::jsonb,
  '{"1 <= s.length <= 2 * 10^5","s consists only of printable ASCII characters."}'
),
(
  'CodeForge Binary Tree Traversal',
  'codeforge-binary-tree-traversal',
  'medium',
  '{"tree","binary-tree","recursion"}',
  72.3,
  '{""}',
  'codeforge',
  'Perform inorder traversal of a binary tree and return the list of node values.',
  '[{"input":"root = [1,null,2,3]","output":"[1,3,2]","explanation":"Inorder traversal visits left subtree, then root, then right subtree."},{"input":"root = []","output":"[]","explanation":"Empty tree has no nodes to visit."}]'::jsonb,
  '{"The number of nodes in the tree is in the range [0, 100].","-100 <= Node.val <= 100"}'
),
(
  'Jump Game',
  'jump-game',
  'medium',
  '{"array","greedy","dynamic-programming"}',
  37.8,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'You are given an integer array nums where each element represents the maximum jump length at that position.',
  '[{"input":"[2,3,1,1,4]","output":"true","explanation":"Jump 1 step from index 0 to 1, then 3 steps to the last index."},{"input":"[3,2,1,0,4]","output":"false","explanation":"Cannot reach the last index."}]'::jsonb,
  '{"1 <= nums.length <= 10^4","0 <= nums[i] <= 10^5"}'
),
(
  'Merge Intervals',
  'merge-intervals',
  'medium',
  '{"array","sorting"}',
  43.2,
  '{"Facebook","Amazon","Google"}',
  'leetcode',
  'Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals.',
  '[{"input":"[[1,3],[2,6],[8,10],[15,18]]","output":"[[1,6],[8,10],[15,18]]","explanation":"Intervals [1,3] and [2,6] overlap, merge them into [1,6]."},{"input":"[[1,4],[4,5]]","output":"[[1,5]]","explanation":"Intervals [1,4] and [4,5] overlap, merge them into [1,5]."}]'::jsonb,
  '{"1 <= intervals.length <= 10^4","intervals[i].length == 2","0 <= starti <= endi <= 10^4"}'
),
(
  'Insert Interval',
  'insert-interval',
  'medium',
  '{"array"}',
  38.7,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'You are given an array of non-overlapping intervals and a new interval. Insert the new interval and merge if necessary.',
  '[{"input":"[[1,3],[6,9]], [2,5]","output":"[[1,5],[6,9]]","explanation":"New interval [2,5] overlaps with [1,3], merge to [1,5]."},{"input":"[[1,2],[3,5],[6,7],[8,10],[12,16]], [4,8]","output":"[[1,2],[3,10],[12,16]]","explanation":"New interval [4,8] overlaps with [3,5],[6,7],[8,10], merge to [3,10]."}]'::jsonb,
  '{"0 <= intervals.length <= 10^4","intervals[i].length == 2","0 <= starti <= endi <= 10^5"}'
),
(
  'Spiral Matrix II',
  'spiral-matrix-ii',
  'medium',
  '{"array","matrix","simulation"}',
  58.1,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a positive integer n, generate an n x n matrix filled with elements from 1 to n^2 in spiral order.',
  '[{"input":"n = 3","output":"[[1,2,3],[8,9,4],[7,6,5]]","explanation":"3x3 matrix filled in spiral order."},{"input":"n = 1","output":"[[1]]","explanation":"1x1 matrix with single element."}]'::jsonb,
  '{"1 <= n <= 20"}'
),
(
  'Jump Game II',
  'jump-game-ii',
  'medium',
  '{"array","greedy"}',
  34.7,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given an array of non-negative integers nums where each element represents the maximum jump length at that position, find the minimum number of jumps to reach the last index.',
  '[{"input":"[2,3,1,1,4]","output":"2","explanation":"Jump 1 step from index 0 to 1, then 3 steps to the last index."},{"input":"[2,3,0,1,4]","output":"2","explanation":"Jump 1 step from index 0 to 1, then 3 steps to the last index."}]'::jsonb,
  '{"1 <= nums.length <= 10^4","0 <= nums[i] <= 10^5"}'
),
(
  'Permutation Sequence',
  'permutation-sequence',
  'hard',
  '{"math","backtracking"}',
  41.2,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'The set [1, 2, 3, ..., n] contains a total of n! unique permutations. Return the kth permutation sequence.',
  '[{"input":"n = 3, k = 3","output":"\"213\"","explanation":"Permutations are [\"123\",\"132\",\"213\",\"231\",\"312\",\"321\"], 3rd is \"213\"."},{"input":"n = 4, k = 9","output":"\"2314\"","explanation":"9th permutation in the sequence."}]'::jsonb,
  '{"1 <= n <= 9","1 <= k <= n!"}'
),
(
  'Rotate List',
  'rotate-list',
  'medium',
  '{"linked-list"}',
  35.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given the head of a linked list, rotate the list to the right by k places.',
  '[{"input":"[1,2,3,4,5], k = 2","output":"[4,5,1,2,3]","explanation":"Rotate right by 2 positions."},{"input":"[0,1,2], k = 4","output":"[2,0,1]","explanation":"Rotate right by 4 positions (equivalent to 1 position)."}]'::jsonb,
  '{"The number of nodes in the list is in the range [0, 500].","0 <= Node.val <= 1000","0 <= k <= 2 * 10^9"}'
),
(
  'Unique Paths',
  'unique-paths',
  'medium',
  '{"math","dynamic-programming","combinatorics"}',
  58.9,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'There is a robot on an m x n grid. The robot can only move down or right. Find the number of unique paths to reach the bottom-right corner.',
  '[{"input":"m = 3, n = 7","output":"28","explanation":"There are 28 unique paths from top-left to bottom-right."},{"input":"m = 3, n = 2","output":"3","explanation":"There are 3 unique paths from top-left to bottom-right."}]'::jsonb,
  '{"1 <= m, n <= 100","The answer will fit in a 32-bit integer."}'
),
(
  'Unique Paths II',
  'unique-paths-ii',
  'medium',
  '{"array","dynamic-programming","matrix"}',
  42.3,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'A robot is located at the top-left corner of a grid with obstacles. Find the number of unique paths to reach the bottom-right corner.',
  '[{"input":"[[0,0,0],[0,1,0],[0,0,0]]","output":"2","explanation":"There is 1 obstacle in the middle of the grid."},{"input":"[[0,1],[0,0]]","output":"1","explanation":"Only one path possible avoiding the obstacle."}]'::jsonb,
  '{"m == obstacleGrid.length","n == obstacleGrid[i].length","1 <= m, n <= 100","obstacleGrid[i][j] is 0 or 1"}'
),
(
  'Minimum Path Sum',
  'minimum-path-sum',
  'medium',
  '{"array","dynamic-programming","matrix"}',
  56.4,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'Given a grid of non-negative numbers, find a path from top-left to bottom-right that minimizes the sum of all numbers along its path.',
  '[{"input":"[[1,3,1],[1,5,1],[4,2,1]]","output":"7","explanation":"Path 1→3→1→1→1 minimizes the sum to 7."},{"input":"[[1,2,3],[4,5,6]]","output":"12","explanation":"Path 1→2→3→6 minimizes the sum to 12."}]'::jsonb,
  '{"m == grid.length","n == grid[i].length","1 <= m, n <= 200","0 <= grid[i][j] <= 100"}'
),
(
  'Valid Sudoku',
  'valid-sudoku',
  'medium',
  '{"array","matrix","hash-table"}',
  51.2,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Determine if a 9 x 9 Sudoku board is valid. Only the filled cells need to be validated.',
  '[{"input":"[[\"5\",\"3\",\".\",\".\",\"7\",\".\",\".\",\".\",\".\"],[\"6\",\".\",\".\",\"1\",\"9\",\"5\",\".\",\".\",\".\"],[\".\",\"9\",\"8\",\".\",\".\",\".\",\".\",\"6\",\".\"],[\"8\",\".\",\".\",\".\",\"6\",\".\",\".\",\".\",\"3\"],[\"4\",\".\",\".\",\"8\",\".\",\"3\",\".\",\".\",\"1\"],[\"7\",\".\",\".\",\".\",\"2\",\".\",\".\",\".\",\"6\"],[\".\",\"6\",\".\",\".\",\".\",\".\",\"2\",\"8\",\".\"],[\".\",\".\",\".\",\"4\",\"1\",\"9\",\".\",\".\",\"5\"],[\".\",\".\",\".\",\".\",\"8\",\".\",\".\",\"7\",\"9\"]]","output":"true","explanation":"The board follows Sudoku rules."}]'::jsonb,
  '{"board.length == 9","board[i].length == 9","board[i][j] is a digit or ''.''"}'
),
(
  'Sudoku Solver',
  'sudoku-solver',
  'hard',
  '{"array","backtracking","matrix"}',
  47.8,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'Write a program to solve a Sudoku puzzle by filling the empty cells.',
  '[{"input":"[[\"5\",\"3\",\".\",\".\",\"7\",\".\",\".\",\".\",\".\"],[\"6\",\".\",\".\",\"1\",\"9\",\"5\",\".\",\".\",\".\"],[\".\",\"9\",\"8\",\".\",\".\",\".\",\".\",\"6\",\".\"],[\"8\",\".\",\".\",\".\",\"6\",\".\",\".\",\".\",\"3\"],[\"4\",\".\",\".\",\"8\",\".\",\"3\",\".\",\".\",\"1\"],[\"7\",\".\",\".\",\".\",\"2\",\".\",\".\",\".\",\"6\"],[\".\",\"6\",\".\",\".\",\".\",\".\",\"2\",\"8\",\".\"],[\".\",\".\",\".\",\"4\",\"1\",\"9\",\".\",\".\",\"5\"],[\".\",\".\",\".\",\".\",\"8\",\".\",\".\",\"7\",\"9\"]]","output":"Solved board","explanation":"All empty cells filled with valid digits."}]'::jsonb,
  '{"board.length == 9","board[i].length == 9","board[i][j] is a digit or ''.''"}'
),
(
  'Decode Ways',
  'decode-ways',
  'medium',
  '{"string","dynamic-programming"}',
  32.4,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given a string s containing only digits, return the number of ways to decode it.',
  '[{"input":"\"12\"","output":"2","explanation":"Could be decoded as \"AB\" (1 2) or \"L\" (12)."},{"input":"\"226\"","output":"3","explanation":"Could be decoded as \"BZ\", \"VF\", or \"BBF\"."},{"input":"\"0\"","output":"0","explanation":"No valid decodings."}]'::jsonb,
  '{"1 <= s.length <= 100","s contains only digits."}'
),
(
  'Binary Tree Maximum Path Sum',
  'binary-tree-maximum-path-sum',
  'hard',
  '{"tree","depth-first-search","dynamic-programming"}',
  35.7,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'A path in a binary tree is a sequence of nodes where each pair of adjacent nodes has an edge connecting them. Find the maximum path sum.',
  '[{"input":"[1,2,3]","output":"6","explanation":"Optimal path is 2->1->3 with sum 6."},{"input":"[-10,9,20,null,null,15,7]","output":"42","explanation":"Optimal path is 15->20->7 with sum 42."}]'::jsonb,
  '{"The number of nodes in the tree is in the range [1, 3 * 10^4].","-1000 <= Node.val <= 1000"}'
),
(
  'Best Time to Buy and Sell Stock',
  'best-time-to-buy-and-sell-stock',
  'easy',
  '{"array","dynamic-programming"}',
  54.3,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'You are given an array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit you can achieve.',
  '[{"input":"[7,1,5,3,6,4]","output":"5","explanation":"Buy on day 2 (price=1) and sell on day 5 (price=6), profit = 6-1 = 5."},{"input":"[7,6,4,3,1]","output":"0","explanation":"No profitable transaction possible."}]'::jsonb,
  '{"1 <= prices.length <= 10^5","0 <= prices[i] <= 10^4"}'
),
(
  'Best Time to Buy and Sell Stock II',
  'best-time-to-buy-and-sell-stock-ii',
  'medium',
  '{"array","dynamic-programming","greedy"}',
  61.2,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Find the maximum profit you can achieve with as many transactions as you like.',
  '[{"input":"[7,1,5,3,6,4]","output":"7","explanation":"Buy on day 2 (price=1) and sell on day 3 (price=5), profit = 4. Then buy on day 4 (price=3) and sell on day 5 (price=6), profit = 3. Total profit = 4+3 = 7."},{"input":"[1,2,3,4,5]","output":"4","explanation":"Buy on day 1 (price=1) and sell on day 5 (price=5), profit = 4."}]'::jsonb,
  '{"1 <= prices.length <= 3 * 10^4","0 <= prices[i] <= 10^4"}'
),
(
  'Triangle',
  'triangle',
  'medium',
  '{"array","dynamic-programming"}',
  48.9,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a triangle array, return the minimum path sum from top to bottom.',
  '[{"input":"[[2],[3,4],[6,5,7],[4,1,8,3]]","output":"11","explanation":"The minimum path sum from top to bottom is 2 + 3 + 5 + 1 = 11."}]'::jsonb,
  '{"1 <= triangle.length <= 200","triangle[i].length == i + 1","-10^4 <= triangle[i][j] <= 10^4"}'
),
(
  'Word Break',
  'word-break',
  'medium',
  '{"hash-table","string","dynamic-programming"}',
  42.3,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of dictionary words.',
  '[{"input":"s = \"leetcode\", wordDict = [\"leet\",\"code\"]","output":"true","explanation":"Can be segmented as \"leet code\"."},{"input":"s = \"applepenapple\", wordDict = [\"apple\",\"pen\"]","output":"true","explanation":"Can be segmented as \"apple pen apple\"."},{"input":"s = \"catsandog\", wordDict = [\"cats\",\"dog\",\"sand\",\"and\",\"cat\"]","output":"false","explanation":"Cannot be segmented."}]'::jsonb,
  '{"1 <= s.length <= 300","1 <= wordDict.length <= 1000","1 <= wordDict[i].length <= 20","s and wordDict[i] consist of only lowercase English letters."}'
),
(
  'Word Break II',
  'word-break-ii',
  'hard',
  '{"hash-table","string","backtracking","dynamic-programming"}',
  38.7,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Return all possible sentences in which the string can be segmented.',
  '[{"input":"s = \"catsanddog\", wordDict = [\"cat\",\"cats\",\"and\",\"sand\",\"dog\"]","output":"[\"cats and dog\",\"cat sand dog\"]","explanation":"All possible segmentations."},{"input":"s = \"pineapplepenapple\", wordDict = [\"apple\",\"pen\",\"applepen\",\"pine\",\"pineapple\"]","output":"[\"pine apple pen apple\",\"pineapple pen apple\",\"pine applepen apple\"]","explanation":"All possible segmentations."}]'::jsonb,
  '{"1 <= s.length <= 20","1 <= wordDict.length <= 1000","1 <= wordDict[i].length <= 10"}'
),
(
  'Gas Station',
  'gas-station',
  'medium',
  '{"array","greedy"}',
  41.8,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'There are n gas stations along a circular route. Find the starting gas station index so you can travel around the circuit once.',
  '[{"input":"gas = [1,2,3,4,5], cost = [3,4,5,1,2]","output":"3","explanation":"Start at station 3 (index 3) and fill up with 4 units of gas."},{"input":"gas = [2,3,4], cost = [3,4,3]","output":"-1","explanation":"Cannot travel around the circuit."}]'::jsonb,
  '{"gas.length == n","cost.length == n","1 <= n <= 10^4","0 <= gas[i], cost[i] <= 10^4"}'
),
(
  'Chef and Divisors Tree',
  'chef-and-divisors-tree',
  'medium',
  '{"math","number-theory"}',
  45.6,
  '{""}',
  'codechef',
  'Given an integer N, find the sum of all divisors of N including 1 and N itself.',
  '[{"input":"N = 6","output":"12","explanation":"Divisors of 6 are 1, 2, 3, 6. Sum = 1+2+3+6 = 12."},{"input":"N = 5","output":"6","explanation":"Divisors of 5 are 1, 5. Sum = 1+5 = 6."}]'::jsonb,
  '{"1 <= N <= 10^6"}'
),
(
  'Maximum Sum of Subarray',
  'maximum-sum-of-subarray',
  'easy',
  '{"array","kadane"}',
  68.4,
  '{""}',
  'codeforces',
  'Given an array of integers, find the maximum sum of any non-empty subarray.',
  '[{"input":"[-1, -2, -3, -4, -5]","output":"-1","explanation":"Maximum sum is -1 (single element)."},{"input":"[1, 2, 3, -2, 5]","output":"9","explanation":"Maximum sum is 1+2+3-2+5 = 9."}]'::jsonb,
  '{"1 <= n <= 10^5","-10^9 <= a[i] <= 10^9"}'
),
(
  'Polycarp and Sums of Digits',
  'polycarp-and-sums-of-digits',
  'easy',
  '{"math","implementation"}',
  72.1,
  '{""}',
  'codeforces',
  'Given a number N, find the sum of its digits. If the sum is a single digit, output it. Otherwise, repeat the process.',
  '[{"input":"N = 9875","output":"2","explanation":"9+8+7+5 = 29, then 2+9 = 11, then 1+1 = 2."},{"input":"N = 123","output":"6","explanation":"1+2+3 = 6."}]'::jsonb,
  '{"1 <= N <= 10^18"}'
),
(
  'Find the Largest Number',
  'find-the-largest-number',
  'easy',
  '{"array","sorting"}',
  81.3,
  '{""}',
  'gfg',
  'Given an array of integers, find the largest element in the array.',
  '[{"input":"[1, 8, 7, 56, 90]","output":"90","explanation":"90 is the largest element in the array."},{"input":"[5, 5, 5, 5]","output":"5","explanation":"All elements are equal, so 5 is the largest."}]'::jsonb,
  '{"1 <= N <= 10^5","1 <= arr[i] <= 10^9"}'
),
(
  'Check for Balanced Parentheses',
  'check-for-balanced-parentheses',
  'easy',
  '{"string","stack"}',
  64.7,
  '{""}',
  'gfg',
  'Given a string of parentheses, check if the parentheses are balanced.',
  '[{"input":"\"{([])}\"","output":"true","explanation":"All brackets are properly nested and balanced."},{"input":"\"([)]\"","output":"false","explanation":"Brackets are not properly nested."}]'::jsonb,
  '{"1 <= s.length <= 10^5","String contains only characters: (), {}, []"}'
),
(
  'Frequency of Elements',
  'frequency-of-elements',
  'easy',
  '{"array","hash-table"}',
  73.2,
  '{""}',
  'hackerrank',
  'Given an array, count the frequency of each element in the array.',
  '[{"input":"[1, 2, 8, 5, 1, 8, 8, 8, 9]","output":"1:2, 2:1, 5:1, 8:4, 9:1","explanation":"Frequency of each element in the array."},{"input":"[10, 10, 10]","output":"10:3","explanation":"Element 10 appears 3 times."}]'::jsonb,
  '{"1 <= N <= 10^5","1 <= arr[i] <= 10^9"}'
),
(
  'Two Characters',
  'two-characters',
  'medium',
  '{"string","hash-table"}',
  52.4,
  '{""}',
  'hackerrank',
  'Given a string, delete characters until the string contains no two equal adjacent characters. Find the maximum length possible.',
  '[{"input":"\"beabeefeab\"","output":"5","explanation":"Delete characters to form \"babab\" or \"bcbcb\" with length 5."},{"input":"\"asvkdcfi\"","output":"2","explanation":"Any two different characters can form a valid string of length 2."}]'::jsonb,
  '{"1 <= s.length <= 10^5","s contains only lowercase English letters."}'
),
(
  'CodeForge Matrix Diagonal Sum',
  'codeforge-matrix-diagonal-sum',
  'easy',
  '{"matrix","array"}',
  76.8,
  '{""}',
  'codeforge',
  'Given a square matrix, return the sum of the elements on the main diagonal and anti-diagonal.',
  '[{"input":"[[1,2,3],[4,5,6],[7,8,9]]","output":"25","explanation":"Main diagonal: 1+5+9=15, Anti-diagonal: 3+5+7=15, Center counted once: 15+15-5=25."},{"input":"[[1,2],[3,4]]","output":"10","explanation":"Main diagonal: 1+4=5, Anti-diagonal: 2+3=5, Total: 10."}]'::jsonb,
  '{"1 <= n <= 100","-100 <= matrix[i][j] <= 100"}'
),
(
  'CodeForge String Compression',
  'codeforge-string-compression',
  'medium',
  '{"string","two-pointers"}',
  62.3,
  '{""}',
  'codeforge',
  'Given a string, compress it by replacing consecutive characters with the character followed by its count.',
  '[{"input":"\"aaabcccccaaa\"","output":"\"a3b1c5a3\"","explanation":"Compressed string with character counts."},{"input":"\"abcd\"","output":"\"a1b1c1d1\"","explanation":"Each character appears once."}]'::jsonb,
  '{"1 <= s.length <= 10^5","s consists of only lowercase English letters."}'
),
(
  'CodeForge Binary Search Tree Validation',
  'codeforge-bst-validation',
  'medium',
  '{"tree","binary-search-tree","recursion"}',
  58.7,
  '{""}',
  'codeforge',
  'Given the root of a binary tree, determine if it is a valid binary search tree.',
  '[{"input":"[2,1,3]","output":"true","explanation":"Valid BST with root 2, left child 1, right child 3."},{"input":"[5,1,4,null,null,3,6]","output":"false","explanation":"Not a valid BST as 3 is in the right subtree of 5 but less than 5."}]'::jsonb,
  '{"The number of nodes in the tree is in the range [1, 10^4].","-2^31 <= Node.val <= 2^31 - 1"}'
),
(
  'Candy',
  'candy',
  'hard',
  '{"array","greedy"}',
  34.2,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'There are n children standing in a line. Each child must be assigned at least one candy. Children with higher ratings get more candies than their neighbors.',
  '[{"input":"[1,0,2]","output":"5","explanation":"Second child gets 1 candy, first and third get 2 each."},{"input":"[1,2,2]","output":"4","explanation":"First child gets 1 candy, second and third get 2 each."}]'::jsonb,
  '{"n == ratings.length","1 <= n <= 2 * 10^4","0 <= ratings[i] <= 2 * 10^4"}'
),
(
  'Copy List with Random Pointer',
  'copy-list-with-random-pointer',
  'medium',
  '{"linked-list","hash-table"}',
  42.7,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'A linked list of length n is given such that each node contains an additional random pointer. Construct a deep copy of the list.',
  '[{"input":"[[7,null],[13,0],[11,4],[10,2],[1,0]]","output":"[[7,null],[13,0],[11,4],[10,2],[1,0]]","explanation":"Deep copy of the linked list with random pointers."}]'::jsonb,
  '{"0 <= n <= 1000","-10^4 <= Node.val <= 10^4","Node.random is null or points to a node in the same linked list."}'
),
(
  'Word Ladder',
  'word-ladder',
  'hard',
  '{"string","breadth-first-search","hash-table"}',
  35.8,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given two words beginWord and endWord, and a dictionary wordList, return the length of the shortest transformation sequence.',
  '[{"input":"beginWord = \"hit\", endWord = \"cog\", wordList = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]","output":"5","explanation":"One shortest transformation sequence is \"hit\" -> \"hot\" -> \"dot\" -> \"dog\" -> \"cog\"."},{"input":"beginWord = \"hit\", endWord = \"cog\", wordList = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\"]","output":"0","explanation":"No possible transformation."}]'::jsonb,
  '{"1 <= beginWord.length <= 10","endWord.length == beginWord.length","1 <= wordList.length <= 5000","wordList[i].length == beginWord.length"}'
),
(
  'LRU Cache',
  'lru-cache',
  'medium',
  '{"hash-table","linked-list","design"}',
  36.4,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.',
  '[{"input":"[\"LRUCache\",\"put\",\"put\",\"get\",\"put\",\"get\",\"put\",\"get\",\"get\",\"get\"]\n[[2],[1,1],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]","output":"[null,null,null,1,null,-1,null,-1,3,4]","explanation":"LRU Cache operations with capacity 2."}]'::jsonb,
  '{"1 <= capacity <= 3000","0 <= key <= 3000","0 <= value <= 10^4","At most 2 * 10^5 calls will be made to get and put."}'
),
(
  'Surrounded Regions',
  'surrounded-regions',
  'medium',
  '{"array","depth-first-search","breadth-first-search","matrix","union-find"}',
  43.2,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given an m x n matrix board containing ''X'' and ''O'', capture all regions that are 4-directionally surrounded by ''X''.',
  '[{"input":"[[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"O\",\"O\",\"X\"],[\"X\",\"X\",\"O\",\"X\"],[\"X\",\"X\",\"X\",\"X\"]]","output":"[[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"]]","explanation":"All surrounded O regions are captured."}]'::jsonb,
  '{"m == board.length","n == board[i].length","1 <= m, n <= 200","board[i][j] is either ''X'' or ''O''"}'
),
(
  'House Robber',
  'house-robber',
  'medium',
  '{"array","dynamic-programming"}',
  48.7,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed.',
  '[{"input":"[1,2,3,1]","output":"4","explanation":"Rob house 1 (money=1) and house 3 (money=3), total = 4."},{"input":"[2,7,9,3,1]","output":"12","explanation":"Rob house 1 (money=2), house 3 (money=9), and house 5 (money=1), total = 12."}]'::jsonb,
  '{"1 <= nums.length <= 100","0 <= nums[i] <= 400"}'
),
(
  'House Robber II',
  'house-robber-ii',
  'medium',
  '{"array","dynamic-programming"}',
  41.3,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'A robber is planning to rob houses along a street. Each house has a certain amount of money stashed. Houses are arranged in a circle.',
  '[{"input":"[2,3,2]","output":"3","explanation":"Cannot rob adjacent houses, so rob house 2 (money=3)."},{"input":"[1,2,3,1]","output":"4","explanation":"Rob house 1 (money=1) and house 3 (money=3), total = 4."}]'::jsonb,
  '{"1 <= nums.length <= 100","1 <= nums[i] <= 1000"}'
),
(
  'House Robber III',
  'house-robber-iii',
  'medium',
  '{"tree","depth-first-search","dynamic-programming"}',
  52.4,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'The thief has found himself a new place for his thievery again. There is only one entrance to this area, called the root.',
  '[{"input":"[3,2,3,null,3,null,1]","output":"7","explanation":"Rob houses with money 3 + 3 + 1 = 7."},{"input":"[3,4,5,1,3,null,1]","output":"9","explanation":"Rob houses with money 4 + 5 = 9."}]'::jsonb,
  '{"The number of nodes in the tree is in the range [1, 10^4].","0 <= Node.val <= 10^4"}'
),
(
  'Palindrome Partitioning',
  'palindrome-partitioning',
  'medium',
  '{"string","backtracking","dynamic-programming"}',
  68.3,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a string s, partition s such that every substring of the partition is a palindrome. Return all possible palindrome partitioning of s.',
  '[{"input":"\"aab\"","output":"[[\"a\",\"a\",\"b\"],[\"aa\",\"b\"]]","explanation":"All possible palindrome partitions."},{"input":"\"a\"","output":"[[\"a\"]]","explanation":"Single character is always a palindrome."}]'::jsonb,
  '{"1 <= s.length <= 16","s consists of only lowercase English letters."}'
),
(
  'Palindrome Partitioning II',
  'palindrome-partitioning-ii',
  'hard',
  '{"string","dynamic-programming"}',
  38.7,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'Given a string s, cut s into pieces such that every piece is a palindrome. Return the minimum number of cuts needed.',
  '[{"input":"\"aab\"","output":"1","explanation":"The palindrome partitioning [\"aa\",\"b\"] could be made using 1 cut."},{"input":"\"a\"","output":"0","explanation":"No cut needed as it''s already a palindrome."},{"input":"\"ab\"","output":"1","explanation":"The palindrome partitioning [\"a\",\"b\"] could be made using 1 cut."}]'::jsonb,
  '{"1 <= s.length <= 2000","s consists of only lowercase English letters."}'
),
(
  'Decode Ways II',
  'decode-ways-ii',
  'hard',
  '{"string","dynamic-programming"}',
  28.3,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given a string s containing digits and ''*'' characters, return the number of ways to decode it.',
  '[{"input":"\"*\"","output":"9","explanation":"Could represent any digit from 1 to 9."},{"input":"\"1*\"","output":"18","explanation":"Could be 11, 12, ..., 19."},{"input":"\"2*\"","output":"15","explanation":"Could be 21, 22, ..., 26."}]'::jsonb,
  '{"1 <= s.length <= 100","s contains only digits and ''*'' characters."}'
),
(
  'Subsets',
  'subsets',
  'medium',
  '{"array","backtracking","bit-manipulation"}',
  67.8,
  '{"Facebook","Amazon","Google"}',
  'leetcode',
  'Given an integer array nums of unique elements, return all possible subsets (the power set).',
  '[{"input":"[1,2,3]","output":"[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]","explanation":"All possible subsets of [1,2,3]."},{"input":"[0]","output":"[[],[0]]","explanation":"All possible subsets of [0]."}]'::jsonb,
  '{"1 <= nums.length <= 10","-10 <= nums[i] <= 10","All elements of nums are unique."}'
),
(
  'Subsets II',
  'subsets-ii',
  'medium',
  '{"array","backtracking","bit-manipulation"}',
  58.7,
  '{"Facebook","Amazon","Google"}',
  'leetcode',
  'Given an integer array nums that may contain duplicates, return all possible subsets.',
  '[{"input":"[1,2,2]","output":"[[],[1],[2],[1,2],[2,2],[1,2,2]]","explanation":"All possible subsets without duplicates."},{"input":"[0]","output":"[[],[0]]","explanation":"All possible subsets of [0]."}]'::jsonb,
  '{"1 <= nums.length <= 10","-10 <= nums[i] <= 10"}'
),
(
  'Word Search II',
  'word-search-ii',
  'hard',
  '{"array","backtracking","string","trie"}',
  35.9,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given an m x n board of characters and a list of words, return all words that can be found in the board.',
  '[{"input":"board = [[\"o\",\"a\",\"a\",\"n\"],[\"e\",\"t\",\"a\",\"e\"],[\"i\",\"h\",\"k\",\"r\"],[\"i\",\"f\",\"l\",\"v\"]], words = [\"oath\",\"pea\",\"eat\",\"rain\"]","output":"[\"oath\",\"eat\"]","explanation":"Words found in the board."}]'::jsonb,
  '{"m == board.length","n == board[i].length","1 <= m, n <= 12","1 <= words.length <= 3 * 10^4","1 <= words[i].length <= 10"}'
),
(
  'Distinct Subsequences',
  'distinct-subsequences',
  'hard',
  '{"string","dynamic-programming"}',
  42.3,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given two strings s and t, return the number of distinct subsequences of s which equals t.',
  '[{"input":"s = \"rabbbit\", t = \"rabbit\"","output":"3","explanation":"Three ways to form \"rabbit\" from \"rabbbit\"."},{"input":"s = \"babgbag\", t = \"bag\"","output":"5","explanation":"Five ways to form \"bag\" from \"babgbag\"."}]'::jsonb,
  '{"1 <= s.length, t.length <= 1000","s and t consist of English letters."}'
),
(
  'Minimum Insertion Steps to Make a String Palindrome',
  'minimum-insertion-steps-to-make-a-string-palindrome',
  'hard',
  '{"string","dynamic-programming"}',
  61.2,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'Given a string s, return the minimum number of insertions needed to make s a palindrome.',
  '[{"input":"\"zzazz\"","output":"0","explanation":"Already a palindrome."},{"input":"\"mbadm\"","output":"2","explanation":"Insert \"ab\" to make \"mbadbam\" palindrome."},{"input":"\"leetcode\"","output":"5","explanation":"Insert \"etce\" to make \"leetcodetecelet\" palindrome."}]'::jsonb,
  '{"1 <= s.length <= 500","s consists of lowercase English letters."}'
),
(
  'Edit Distance',
  'edit-distance',
  'medium',
  '{"string","dynamic-programming"}',
  54.7,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given two strings word1 and word2, return the minimum number of operations required to convert word1 to word2.',
  '[{"input":"word1 = \"horse\", word2 = \"ros\"","output":"3","explanation":"Replace h with r, delete o, insert e."},{"input":"word1 = \"intention\", word2 = \"execution\"","output":"5","explanation":"Multiple operations needed."}]'::jsonb,
  '{"0 <= word1.length, word2.length <= 500","word1 and word2 consist of lowercase English letters."}'
),
(
  'Ones and Zeroes',
  'ones-and-zeroes',
  'medium',
  '{"array","string","dynamic-programming"}',
  58.1,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'You are given an array of binary strings strs and two integers m and n. Return the size of the largest subset of strs.',
  '[{"input":"strs = [\"10\",\"0001\",\"111001\",\"1\",\"0\"], m = 5, n = 3","output":"4","explanation":"Largest subset has 4 strings."},{"input":"strs = [\"10\",\"0\",\"1\"], m = 1, n = 1","output":"2","explanation":"Largest subset has 2 strings."}]'::jsonb,
  '{"1 <= strs.length <= 600","1 <= strs[i].length <= 100","strs[i] consists only of ''0'' and ''1''","0 <= m, n <= 100"}'
),
(
  'Find Minimum in Rotated Sorted Array',
  'find-minimum-in-rotated-sorted-array',
  'medium',
  '{"array","binary-search"}',
  47.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a rotated sorted array of unique elements, return the minimum element.',
  '[{"input":"[3,4,5,1,2]","output":"1","explanation":"The minimum element is 1."},{"input":"[4,5,6,7,0,1,2]","output":"0","explanation":"The minimum element is 0."},{"input":"[11,13,15,17,2,5,6,8,10]","output":"2","explanation":"The minimum element is 2."}]'::jsonb,
  '{"n == nums.length","1 <= n <= 5000","-5000 <= nums[i] <= 5000","All elements of nums are unique.","nums is sorted and rotated."}'
),
(
  'Find Minimum in Rotated Sorted Array II',
  'find-minimum-in-rotated-sorted-array-ii',
  'hard',
  '{"array","binary-search"}',
  41.3,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a rotated sorted array that may contain duplicates, return the minimum element.',
  '[{"input":"[1,3,5]","output":"1","explanation":"The minimum element is 1."},{"input":"[2,2,2,0,1]","output":"0","explanation":"The minimum element is 0."}]'::jsonb,
  '{"n == nums.length","1 <= n <= 5000","-5000 <= nums[i] <= 5000","nums is sorted and rotated."}'
),
(
  'Chef and Prime Numbers',
  'chef-and-prime-numbers',
  'medium',
  '{"math","number-theory","sieve"}',
  42.3,
  '{""}',
  'codechef',
  'Given a range [L, R], find the number of prime numbers in that range.',
  '[{"input":"L = 1, R = 10","output":"4","explanation":"Primes are 2, 3, 5, 7."},{"input":"L = 5, R = 20","output":"6","explanation":"Primes are 5, 7, 11, 13, 17, 19."}]'::jsonb,
  '{"1 <= L <= R <= 10^6"}'
),
(
  'Maximum XOR Subarray',
  'maximum-xor-subarray',
  'medium',
  '{"array","bit-manipulation","trie"}',
  38.7,
  '{""}',
  'codeforces',
  'Given an array of integers, find the maximum XOR of any subarray.',
  '[{"input":"[1, 2, 3]","output":"3","explanation":"Maximum XOR is 1^2 = 3."},{"input":"[8, 1, 2, 12]","output":"15","explanation":"Maximum XOR is 8^7 = 15."}]'::jsonb,
  '{"1 <= n <= 10^5","0 <= a[i] <= 10^9"}'
),
(
  'Divisible Subarrays',
  'divisible-subarrays',
  'easy',
  '{"array","math","prefix-sum"}',
  65.4,
  '{""}',
  'codeforces',
  'Given an array, count the number of subarrays whose sum is divisible by n.',
  '[{"input":"[1, 2, 3, 4, 5]","output":"4","explanation":"Subarrays with sum divisible by 5."},{"input":"[1, 1, 1, 1]","output":"10","explanation":"All subarrays have sum divisible by 4."}]'::jsonb,
  '{"1 <= n <= 10^5","1 <= a[i] <= 10^9"}'
),
(
  'Sort an Array of 0s, 1s and 2s',
  'sort-an-array-of-0s-1s-and-2s',
  'easy',
  '{"array","sorting","two-pointers"}',
  78.9,
  '{""}',
  'gfg',
  'Given an array of size N containing only 0s, 1s, and 2s, sort the array in ascending order.',
  '[{"input":"[0, 2, 1, 2, 0]","output":"[0, 0, 1, 2, 2]","explanation":"Array sorted in ascending order."},{"input":"[0, 1, 0]","output":"[0, 0, 1]","explanation":"Array sorted in ascending order."}]'::jsonb,
  '{"1 <= N <= 10^5","arr[i] is 0, 1, or 2"}'
),
(
  'Kth Largest Element in an Array',
  'kth-largest-element-in-an-array',
  'medium',
  '{"array","heap","sorting"}',
  58.3,
  '{""}',
  'gfg',
  'Given an array of N distinct integers and a number K, find the Kth largest element in the array.',
  '[{"input":"[12, 3, 5, 7, 19], K = 2","output":"12","explanation":"Second largest element is 12."},{"input":"[1, 2, 3, 4, 5], K = 4","output":"2","explanation":"Fourth largest element is 2."}]'::jsonb,
  '{"1 <= N <= 10^4","1 <= K <= N","1 <= arr[i] <= 10^9"}'
),
(
  'Left Rotate an Array by D Places',
  'left-rotate-an-array-by-d-places',
  'easy',
  '{"array","rotation"}',
  72.6,
  '{""}',
  'gfg',
  'Given an array of N integers and a value D, rotate the array left by D positions.',
  '[{"input":"[1,2,3,4,5], D = 2","output":"[3,4,5,1,2]","explanation":"Array rotated left by 2 positions."},{"input":"[2,4,6,8,10], D = 3","output":"[8,10,2,4,6]","explanation":"Array rotated left by 3 positions."}]'::jsonb,
  '{"1 <= N <= 10^5","1 <= D <= N","1 <= arr[i] <= 10^9"}'
),
(
  'Count Triplets',
  'count-triplets',
  'medium',
  '{"array","math","sorting"}',
  45.8,
  '{""}',
  'hackerrank',
  'Given an array of integers, count the number of triplets (i, j, k) such that i < j < k and arr[i] + arr[j] = arr[k].',
  '[{"input":"[1, 2, 3, 4, 5]","output":"4","explanation":"Triplets: (1,2,3), (1,3,4), (2,3,5), (1,4,5)."},{"input":"[1, 1, 1, 1]","output":"4","explanation":"All combinations of three 1s sum to 2, but we need exact matches."}]'::jsonb,
  '{"3 <= n <= 100","1 <= arr[i] <= 1000"}'
),
(
  'Sherlock and Array',
  'sherlock-and-array',
  'easy',
  '{"array","prefix-sum"}',
  81.2,
  '{""}',
  'hackerrank',
  'Given an array, determine if there exists an element such that the sum of elements on its left is equal to the sum of elements on its right.',
  '[{"input":"[1, 2, 3]","output":"NO","explanation":"No such element exists."},{"input":"[1, 2, 3, 3]","output":"YES","explanation":"Element at index 3 (value 3) has left sum 3 and right sum 3."}]'::jsonb,
  '{"1 <= n <= 10^5","1 <= a[i] <= 10^4"}'
),
(
  'CodeForge Graph BFS Traversal',
  'codeforge-graph-bfs-traversal',
  'medium',
  '{"graph","breadth-first-search"}',
  64.7,
  '{""}',
  'codeforge',
  'Given a graph and a starting node, perform BFS traversal and return the order of visited nodes.',
  '[{"input":"graph = [[1,2],[0,3],[0,3],[1,2]], start = 0","output":"[0,1,2,3]","explanation":"BFS traversal starting from node 0."},{"input":"graph = [[1],[0,2],[1,3],[2]], start = 1","output":"[1,0,2,3]","explanation":"BFS traversal starting from node 1."}]'::jsonb,
  '{"1 <= V <= 1000","0 <= E <= V*(V-1)/2","Graph is undirected and connected"}'
),
(
  'CodeForge Stack Implementation',
  'codeforge-stack-implementation',
  'easy',
  '{"stack","design"}',
  87.3,
  '{""}',
  'codeforge',
  'Implement a stack with push, pop, top, and getMin operations in O(1) time.',
  '[{"input":"operations = [\"push\",\"push\",\"getMin\",\"pop\",\"top\"], values = [1,2,null,null,null]","output":"[null,null,1,null,2]","explanation":"Stack operations with minimum tracking."}]'::jsonb,
  '{"1 <= operations <= 10^4","Operations include push, pop, top, getMin"}'
),
(
  'Minimum Number of Platforms',
  'minimum-number-of-platforms',
  'medium',
  '{"array","sorting","greedy"}',
  52.8,
  '{""}',
  'gfg',
  'Given arrival and departure times of trains, find the minimum number of platforms required.',
  '[{"input":"arrivals = [900, 940, 950, 1100, 1500, 1800], departures = [910, 1200, 1130, 1150, 1900, 2000]","output":"3","explanation":"Minimum 3 platforms needed."}]'::jsonb,
  '{"1 <= N <= 50000","1 <= arrival[i] < departure[i] <= 2359"}'
),
(
  'Stock Buy and Sell',
  'stock-buy-and-sell',
  'medium',
  '{"array","greedy"}',
  58.9,
  '{""}',
  'gfg',
  'Given an array of stock prices, find the maximum profit by buying and selling stocks multiple times.',
  '[{"input":"[100, 180, 260, 310, 40, 535, 695]","output":"865","explanation":"Buy at 100 sell at 310, buy at 40 sell at 695."},{"input":"[4, 3, 2, 1]","output":"0","explanation":"No profit possible."}]'::jsonb,
  '{"1 <= N <= 10^5","1 <= price[i] <= 10^5"}'
),
(
  'Chef and Chocolate Distribution',
  'chef-and-chocolate-distribution',
  'easy',
  '{"array","sorting","greedy"}',
  67.4,
  '{""}',
  'codechef',
  'Given N chocolates and M children, distribute chocolates such that each child gets at most one chocolate and the difference between maximum and minimum chocolates is minimized.',
  '[{"input":"chocolates = [7, 3, 2, 4, 9, 12, 56], M = 3","output":"2","explanation":"Give chocolates 2, 3, 4 to minimize difference."}]'::jsonb,
  '{"1 <= N <= 10^5","1 <= M <= N","1 <= chocolates[i] <= 10^9"}'
),
(
  'Team Formation',
  'team-formation',
  'easy',
  '{"array","sorting"}',
  73.6,
  '{""}',
  'codeforces',
  'Given skills of N students, form teams of 2 such that the skill difference is minimized.',
  '[{"input":"[1, 3, 5, 7, 9]","output":"8","explanation":"Teams: (1,3), (5,7), remaining 9. Total difference: 2+2+4=8."}]'::jsonb,
  '{"1 <= N <= 1000","1 <= skill[i] <= 10^9"}'
),
(
  'Beautiful Triplets',
  'beautiful-triplets',
  'easy',
  '{"array","math"}',
  68.2,
  '{""}',
  'hackerrank',
  'Given a sequence and a beautiful difference d, count the number of beautiful triplets.',
  '[{"input":"[1, 2, 4, 5, 7, 8, 10], d = 3","output":"3","explanation":"Beautiful triplets: (1,4,7), (2,5,8), (4,7,10)."}]'::jsonb,
  '{"1 <= n <= 10^5","1 <= d <= 20","1 <= arr[i] <= 10^5"}'
),
(
  'CodeForge Binary Search Implementation',
  'codeforge-binary-search-implementation',
  'easy',
  '{"array","binary-search"}',
  82.4,
  '{""}',
  'codeforge',
  'Implement binary search to find the index of a target element in a sorted array.',
  '[{"input":"[1, 2, 3, 4, 5, 6], target = 4","output":"3","explanation":"Target found at index 3."},{"input":"[1, 3, 5, 7, 9], target = 6","output":"-1","explanation":"Target not found in array."}]'::jsonb,
  '{"1 <= arr.length <= 10^5","1 <= arr[i] <= 10^9","Array is sorted in ascending order"}'
),
(
  'CodeForge Quick Sort',
  'codeforge-quick-sort',
  'medium',
  '{"array","sorting","divide-and-conquer"}',
  71.8,
  '{""}',
  'codeforge',
  'Implement quick sort algorithm to sort an array in ascending order.',
  '[{"input":"[10, 7, 8, 9, 1, 5]","output":"[1, 5, 7, 8, 9, 10]","explanation":"Array sorted using quick sort."},{"input":"[4, 3, 2, 1]","output":"[1, 2, 3, 4]","explanation":"Array sorted using quick sort."}]'::jsonb,
  '{"1 <= arr.length <= 10^5","1 <= arr[i] <= 10^9"}'
),
(
  'CodeForge Merge Sort',
  'codeforge-merge-sort',
  'medium',
  '{"array","sorting","divide-and-conquer"}',
  74.2,
  '{""}',
  'codeforge',
  'Implement merge sort algorithm to sort an array in ascending order.',
  '[{"input":"[12, 11, 13, 5, 6, 7]","output":"[5, 6, 7, 11, 12, 13]","explanation":"Array sorted using merge sort."},{"input":"[38, 27, 43, 3, 9, 82, 10]","output":"[3, 9, 10, 27, 38, 43, 82]","explanation":"Array sorted using merge sort."}]'::jsonb,
  '{"1 <= arr.length <= 10^5","1 <= arr[i] <= 10^9"}'
),
(
  'CodeForge Hash Table Implementation',
  'codeforge-hash-table-implementation',
  'medium',
  '{"hash-table","design"}',
  68.9,
  '{""}',
  'codeforge',
  'Implement a hash table with insert, delete, and search operations.',
  '[{"input":"operations = [\"insert\",\"search\",\"delete\",\"search\"], values = [1,1,1,1]","output":"[null,true,null,false]","explanation":"Hash table operations."}]'::jsonb,
  '{"1 <= operations <= 10^4","1 <= key <= 10^9"}'
),
(
  'CodeForge Priority Queue',
  'codeforge-priority-queue',
  'medium',
  '{"heap","priority-queue","design"}',
  65.7,
  '{""}',
  'codeforge',
  'Implement a priority queue with insert, extractMax, and getMax operations.',
  '[{"input":"operations = [\"insert\",\"insert\",\"getMax\",\"extractMax\",\"getMax\"], values = [10,20,null,null,null]","output":"[null,null,20,20,10]","explanation":"Priority queue operations."}]'::jsonb,
  '{"1 <= operations <= 10^4","1 <= value <= 10^9"}'
),
(
  'Best Time to Buy and Sell Stock III',
  'best-time-to-buy-and-sell-stock-iii',
  'hard',
  '{"array","dynamic-programming"}',
  38.7,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'You are given an array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit with at most two transactions.',
  '[{"input":"[3,3,5,0,0,3,1,4]","output":"6","explanation":"Buy on day 4 (price=0) and sell on day 6 (price=3), then buy on day 7 (price=1) and sell on day 8 (price=4)."}]'::jsonb,
  '{"1 <= prices.length <= 10^5","0 <= prices[i] <= 10^5"}'
),
(
  'Best Time to Buy and Sell Stock IV',
  'best-time-to-buy-and-sell-stock-iv',
  'hard',
  '{"array","dynamic-programming"}',
  31.2,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'You are given an integer k and a prices array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit with at most k transactions.',
  '[{"input":"k = 2, prices = [2,4,1]","output":"2","explanation":"Buy on day 1 (price=2) and sell on day 2 (price=4)."},{"input":"k = 2, prices = [3,2,6,5,0,3]","output":"7","explanation":"Buy on day 2 (price=2) and sell on day 3 (price=6), then buy on day 5 (price=0) and sell on day 6 (price=3)."}]'::jsonb,
  '{"0 <= k <= 100","0 <= prices.length <= 1000","0 <= prices[i] <= 1000"}'
),
(
  'Binary Tree Right Side View',
  'binary-tree-right-side-view',
  'medium',
  '{"tree","depth-first-search","breadth-first-search"}',
  58.3,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given the root of a binary tree, imagine yourself standing on the right side of it. Return the values of the nodes you can see ordered from top to bottom.',
  '[{"input":"[1,2,3,null,5,null,4]","output":"[1,3,4]","explanation":"Right side view of the tree."},{"input":"[1,null,3]","output":"[1,3]","explanation":"Right side view of the tree."}]'::jsonb,
  '{"The number of nodes in the tree is in the range [1, 100].","-100 <= Node.val <= 100"}'
),
(
  'Binary Tree Left Side View',
  'binary-tree-left-side-view',
  'medium',
  '{"tree","depth-first-search","breadth-first-search"}',
  56.7,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given the root of a binary tree, imagine yourself standing on the left side of it. Return the values of the nodes you can see ordered from top to bottom.',
  '[{"input":"[1,2,3,null,5,null,4]","output":"[1,2,5]","explanation":"Left side view of the tree."},{"input":"[1,3]","output":"[1,3]","explanation":"Left side view of the tree."}]'::jsonb,
  '{"The number of nodes in the tree is in the range [1, 100].","-100 <= Node.val <= 100"}'
),
(
  'Number of Islands',
  'number-of-islands',
  'medium',
  '{"array","depth-first-search","breadth-first-search","matrix","union-find"}',
  51.2,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given an m x n 2D grid map of ''1''s (land) and ''0''s (water), count the number of islands.',
  '[{"input":"[[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"1\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"1\",\"1\"]]","output":"3","explanation":"There are 3 islands in the grid."},{"input":"[[\"1\",\"1\",\"1\"],[\"0\",\"1\",\"0\"],[\"1\",\"1\",\"1\"]]","output":"1","explanation":"There is 1 island in the grid."}]'::jsonb,
  '{"m == grid.length","n == grid[i].length","1 <= m, n <= 300","grid[i][j] is either ''0'' or ''1''"}'
),
(
  'Surrounded Regions II',
  'surrounded-regions-ii',
  'hard',
  '{"array","depth-first-search","breadth-first-search","matrix"}',
  42.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a matrix of characters, replace all characters that are not surrounded by ''X'' with ''X''.',
  '[{"input":"[[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"O\",\"O\",\"X\"],[\"X\",\"X\",\"O\",\"X\"],[\"X\",\"X\",\"X\",\"X\"]]","output":"[[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"],[\"X\",\"X\",\"X\",\"X\"]]","explanation":"All surrounded O regions are captured."}]'::jsonb,
  '{"m == board.length","n == board[i].length","1 <= m, n <= 200","board[i][j] is either ''X'' or ''O''"}'
),
(
  'Longest Increasing Subsequence',
  'longest-increasing-subsequence',
  'medium',
  '{"array","binary-search","dynamic-programming"}',
  47.3,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given an integer array nums, return the length of the longest strictly increasing subsequence.',
  '[{"input":"[10,9,2,5,3,7,101,18]","output":"4","explanation":"The longest increasing subsequence is [2,3,7,101]."},{"input":"[0,1,0,3,2,3]","output":"4","explanation":"The longest increasing subsequence is [0,1,2,3]."}]'::jsonb,
  '{"1 <= nums.length <= 2500","-10^4 <= nums[i] <= 10^4"}'
),
(
  'Longest Common Subsequence',
  'longest-common-subsequence',
  'medium',
  '{"string","dynamic-programming"}',
  52.4,
  '{"Facebook","Google","Amazon"}',
  'leetcode',
  'Given two strings text1 and text2, return the length of their longest common subsequence.',
  '[{"input":"text1 = \"abcde\", text2 = \"ace\"","output":"3","explanation":"The longest common subsequence is \"ace\"."},{"input":"text1 = \"abc\", text2 = \"def\"","output":"0","explanation":"No common subsequence."}]'::jsonb,
  '{"1 <= text1.length, text2.length <= 1000","text1 and text2 consist only of lowercase English characters."}'
),
(
  'Maximum Product of Three Numbers',
  'maximum-product-of-three-numbers',
  'easy',
  '{"array","math","sorting"}',
  64.7,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given an integer array nums, find three numbers whose product is maximum and return the maximum product.',
  '[{"input":"[1,2,3]","output":"6","explanation":"Maximum product is 1*2*3 = 6."},{"input":"[1,2,3,4]","output":"24","explanation":"Maximum product is 2*3*4 = 24."},{"input":"[-1,-2,-3]","output":"-6","explanation":"Maximum product is -1*-2*-3 = -6."}]'::jsonb,
  '{"3 <= nums.length <= 10^4","-1000 <= nums[i] <= 1000"}'
),
(
  'Maximum Product of Four Numbers',
  'maximum-product-of-four-numbers',
  'medium',
  '{"array","math","sorting"}',
  58.9,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Given an integer array nums, find four numbers whose product is maximum and return the maximum product.',
  '[{"input":"[1,2,3,4]","output":"24","explanation":"Maximum product is 1*2*3*4 = 24."},{"input":"[-4,-3,-2,-1,60]","output":"720","explanation":"Maximum product is -4*-3*-2*60 = 720."}]'::jsonb,
  '{"4 <= nums.length <= 10^4","-1000 <= nums[i] <= 1000"}'
),
(
  'Palindrome Partitioning III',
  'palindrome-partitioning-iii',
  'hard',
  '{"string","dynamic-programming"}',
  41.2,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'Given a string s, partition s such that every substring of the partition is a palindrome. Return the minimum cuts needed for palindrome partitioning of s.',
  '[{"input":"\"aab\"","output":"1","explanation":"The palindrome partitioning [\"aa\",\"b\"] could be made using 1 cut."},{"input":"\"a\"","output":"0","explanation":"No cut needed as it''s already a palindrome."}]'::jsonb,
  '{"1 <= s.length <= 2000","s consists of only lowercase English letters."}'
),
(
  'Clone Graph',
  'clone-graph',
  'medium',
  '{"graph","depth-first-search","breadth-first-search"}',
  46.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a reference of a node in a connected undirected graph, return a deep copy (clone) of the graph.',
  '[{"input":"adjList = [[2,4],[1,3],[2,4],[1,3]]","output":"[[2,4],[1,3],[2,4],[1,3]]","explanation":"Graph cloned successfully."}]'::jsonb,
  '{"The number of nodes in the graph is in the range [1, 100].","1 <= Node.val <= 100","There are no repeated edges and no self-loops in the graph."}'
),
(
  'Course Schedule',
  'course-schedule',
  'medium',
  '{"graph","depth-first-search","breadth-first-search","topological-sort"}',
  43.7,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. Some courses have prerequisites.',
  '[{"input":"numCourses = 2, prerequisites = [[1,0]]","output":"true","explanation":"Possible to finish both courses."},{"input":"numCourses = 2, prerequisites = [[1,0],[0,1]]","output":"false","explanation":"Impossible to finish both courses due to cycle."}]'::jsonb,
  '{"1 <= numCourses <= 10^5","0 <= prerequisites.length <= 5000","prerequisites[i].length == 2","0 <= ai, bi < numCourses"}'
),
(
  'Course Schedule II',
  'course-schedule-ii',
  'medium',
  '{"graph","depth-first-search","breadth-first-search","topological-sort"}',
  48.3,
  '{"Amazon","Google","Microsoft"}',
  'leetcode',
  'Find a way to finish all courses. Return any order if possible, otherwise return an empty array.',
  '[{"input":"numCourses = 2, prerequisites = [[1,0]]","output":"[0,1]","explanation":"Take course 0 then 1."},{"input":"numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]","output":"[0,1,2,3] or [0,2,1,3]","explanation":"Valid order to finish all courses."}]'::jsonb,
  '{"1 <= numCourses <= 2000","0 <= prerequisites.length <= 5000","prerequisites[i].length == 2","0 <= ai, bi < numCourses"}'
),
(
  'Minimum Height Trees',
  'minimum-height-trees',
  'medium',
  '{"graph","breadth-first-search"}',
  51.6,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given a tree of n nodes labelled from 0 to n-1, and an array of n-1 edges, find all the root labels of Minimum Height Trees (MHTs).',
  '[{"input":"n = 4, edges = [[1,0],[1,2],[1,3]]","output":"[1]","explanation":"Node 1 is the only MHT root."},{"input":"n = 6, edges = [[0,3],[1,3],[2,3],[4,3],[5,4]]","output":"[3,4]","explanation":"Nodes 3 and 4 are MHT roots."}]'::jsonb,
  '{"1 <= n <= 10^4","edges.length == n - 1","0 <= ai, bi < n","The input forms a valid tree."}'
),
(
  'Reconstruct Itinerary',
  'reconstruct-itinerary',
  'hard',
  '{"graph","depth-first-search","eulerian-circuit","hierholzers-algorithm"}',
  38.9,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'You are given a list of airline tickets where tickets[i] = [fromi, toi] represent a departure and arrival airport of a flight.',
  '[{"input":"tickets = [[\"MUC\",\"LHR\"],[\"JFK\",\"MUC\"],[\"SFO\",\"SJC\"],[\"LHR\",\"SFO\"]]","output":"[\"JFK\",\"MUC\",\"LHR\",\"SFO\",\"SJC\"]","explanation":"Valid itinerary using all tickets once."},{"input":"tickets = [[\"JFK\",\"SFO\"],[\"JFK\",\"ATL\"],[\"SFO\",\"ATL\"],[\"ATL\",\"JFK\"],[\"ATL\",\"SFO\"]]","output":"[\"JFK\",\"ATL\",\"JFK\",\"SFO\",\"ATL\",\"SFO\"]","explanation":"Valid itinerary using all tickets once."}]'::jsonb,
  '{"1 <= tickets.length <= 300","tickets[i].length == 2","fromi.length == 3","toi.length == 3","fromi and toi consist of uppercase English letters."}'
),
(
  'Alien Dictionary',
  'alien-dictionary',
  'hard',
  '{"graph","topological-sort"}',
  35.4,
  '{"Google","Microsoft","Amazon"}',
  'leetcode',
  'There is a new alien language. Derive the order of letters from a dictionary of words.',
  '[{"input":"words = [\"wrt\",\"wrf\",\"er\",\"ett\",\"rftt\"]","output":"\"wertf\"","explanation":"Order of letters in alien dictionary."},{"input":"words = [\"z\",\"x\"]","output":"\"zx\"","explanation":"Order of letters in alien dictionary."}]'::jsonb,
  '{"1 <= words.length <= 10^4","1 <= words[i].length <= 100","words[i] consists of only lowercase English letters."}'
),
(
  'Graph Valid Tree',
  'graph-valid-tree',
  'medium',
  '{"graph","depth-first-search","breadth-first-search","union-find"}',
  47.2,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given n nodes labeled from 0 to n-1 and a list of undirected edges, check if these edges form a valid tree.',
  '[{"input":"n = 5, edges = [[0,1],[0,2],[0,3],[1,4]]","output":"true","explanation":"The graph is a valid tree."},{"input":"n = 5, edges = [[0,1],[1,2],[2,3],[1,3],[1,4]]","output":"false","explanation":"The graph contains a cycle."}]'::jsonb,
  '{"1 <= n <= 200","0 <= edges.length <= n * (n - 1) / 2","edges[i].length == 2","0 <= ai, bi < n","ai != bi","There are no self-loops or repeated edges."}'
),
(
  'Connected Components in Undirected Graph',
  'connected-components-in-undirected-graph',
  'medium',
  '{"graph","depth-first-search","breadth-first-search","union-find"}',
  52.8,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given an undirected graph, return the number of connected components in the graph.',
  '[{"input":"n = 5, edges = [[0,1],[1,2],[3,4]]","output":"2","explanation":"Two connected components: {0,1,2} and {3,4}."},{"input":"n = 4, edges = [[0,1],[2,3]]","output":"2","explanation":"Two connected components: {0,1} and {2,3}."}]'::jsonb,
  '{"1 <= n <= 200","0 <= edges.length <= n * (n - 1) / 2","edges[i].length == 2","0 <= ai, bi < n","ai != bi","There are no self-loops or repeated edges."}'
),
(
  'Number of Connected Components in an Undirected Graph',
  'number-of-connected-components-in-an-undirected-graph',
  'medium',
  '{"graph","depth-first-search","breadth-first-search","union-find"}',
  54.3,
  '{"Microsoft","Amazon","Apple"}',
  'leetcode',
  'Given n nodes and edges, return the number of connected components in the undirected graph.',
  '[{"input":"n = 5, edges = [[0,1],[1,2],[3,4]]","output":"2","explanation":"Two connected components."},{"input":"n = 4, edges = []","output":"4","explanation":"Four connected components, each node is isolated."}]'::jsonb,
  '{"1 <= n <= 200","0 <= edges.length <= n * (n - 1) / 2","edges[i].length == 2","0 <= ai, bi < n","ai != bi","There are no self-loops or repeated edges."}'
),
(
  'Chef and Fibonacci',
  'chef-and-fibonacci',
  'medium',
  '{"math","dynamic-programming"}',
  48.7,
  '{""}',
  'codechef',
  'Given N, find the Nth Fibonacci number modulo 10^9+7.',
  '[{"input":"N = 5","output":"5","explanation":"5th Fibonacci number is 5."},{"input":"N = 10","output":"55","explanation":"10th Fibonacci number is 55."}]'::jsonb,
  '{"1 <= N <= 10^18"}'
),
(
  'Maximum Subarray Sum with One Deletion',
  'maximum-subarray-sum-with-one-deletion',
  'medium',
  '{"array","dynamic-programming"}',
  42.3,
  '{""}',
  'codeforces',
  'Given an array, find the maximum subarray sum with the option to delete at most one element.',
  '[{"input":"[1, -2, 0, 3]","output":"4","explanation":"Delete -2 to get subarray [1,0,3] with sum 4."},{"input":"[1, -2, -2, 3]","output":"3","explanation":"Delete -2 to get subarray [1,3] with sum 4, but better to keep [3]."}]'::jsonb,
  '{"1 <= n <= 10^5","-10^4 <= a[i] <= 10^4"}'
),
(
  'Prefix Sum Queries',
  'prefix-sum-queries',
  'easy',
  '{"array","prefix-sum"}',
  67.8,
  '{""}',
  'codeforces',
  'Given an array, answer queries about the sum of elements in a range.',
  '[{"input":"[1, 2, 3, 4, 5], queries = [[1, 3], [2, 5]]","output":"[6, 14]","explanation":"Sum of elements from index 1 to 3 is 6, from 2 to 5 is 14."}]'::jsonb,
  '{"1 <= n <= 10^5","1 <= q <= 10^5","1 <= a[i] <= 10^9"}'
),
(
  'Find the Missing Number',
  'find-the-missing-number',
  'easy',
  '{"array","math"}',
  78.4,
  '{""}',
  'gfg',
  'Given an array of size N-1 with distinct integers from 1 to N, find the missing number.',
  '[{"input":"[1, 2, 3, 5]","output":"4","explanation":"4 is missing from the array."},{"input":"[2, 3, 4, 5]","output":"1","explanation":"1 is missing from the array."}]'::jsonb,
  '{"1 <= N <= 10^5","Array contains distinct integers from 1 to N except one missing number."}'
),
(
  'Find the Duplicate Number',
  'find-the-duplicate-number',
  'medium',
  '{"array","math","two-pointers"}',
  58.9,
  '{""}',
  'gfg',
  'Given an array of size N+1 with integers from 1 to N, find the duplicate number.',
  '[{"input":"[1, 3, 4, 2, 2]","output":"2","explanation":"2 is the duplicate number."},{"input":"[3, 1, 3, 4, 2]","output":"3","explanation":"3 is the duplicate number."}]'::jsonb,
  '{"1 <= N <= 10^5","Array contains integers from 1 to N with exactly one duplicate."}'
),
(
  'Find the First Repeating Element',
  'find-the-first-repeating-element',
  'easy',
  '{"array","hash-table"}',
  71.2,
  '{""}',
  'gfg',
  'Given an array, find the first repeating element in it. Return the index of the first occurrence.',
  '[{"input":"[1, 5, 3, 4, 3, 5, 6]","output":"1","explanation":"5 is the first repeating element, first occurs at index 1."},{"input":"[1, 2, 3, 4, 5]","output":"-1","explanation":"No repeating elements."}]'::jsonb,
  '{"1 <= N <= 10^5","1 <= arr[i] <= 10^5"}'
),
(
  'Merge Two Sorted Arrays',
  'merge-two-sorted-arrays',
  'easy',
  '{"array","two-pointers"}',
  74.6,
  '{""}',
  'hackerrank',
  'Given two sorted arrays, merge them into a single sorted array.',
  '[{"input":"[1, 3, 5], [2, 4, 6]","output":"[1, 2, 3, 4, 5, 6]","explanation":"Merged sorted array."},{"input":"[1, 2, 3], [4, 5, 6]","output":"[1, 2, 3, 4, 5, 6]","explanation":"Merged sorted array."}]'::jsonb,
  '{"1 <= n, m <= 10^5","Both arrays are sorted in ascending order."}'
),
(
  'Counting Sort',
  'counting-sort',
  'easy',
  '{"array","sorting"}',
  82.3,
  '{""}',
  'hackerrank',
  'Implement counting sort to sort an array of non-negative integers.',
  '[{"input":"[4, 2, 2, 8, 3, 3, 1]","output":"[1, 2, 2, 3, 3, 4, 8]","explanation":"Array sorted using counting sort."},{"input":"[6, 5, 4, 3, 2, 1]","output":"[1, 2, 3, 4, 5, 6]","explanation":"Array sorted using counting sort."}]'::jsonb,
  '{"1 <= n <= 10^5","0 <= arr[i] <= 10^5"}'
),
(
  'CodeForge DFS Traversal',
  'codeforge-dfs-traversal',
  'medium',
  '{"graph","depth-first-search"}',
  63.7,
  '{""}',
  'codeforge',
  'Given a graph and a starting node, perform DFS traversal and return the order of visited nodes.',
  '[{"input":"graph = [[1,2],[0,3],[0,3],[1,2]], start = 0","output":"[0,1,3,2]","explanation":"DFS traversal starting from node 0."},{"input":"graph = [[1],[0,2],[1,3],[2]], start = 1","output":"[1,0,2,3]","explanation":"DFS traversal starting from node 1."}]'::jsonb,
  '{"1 <= V <= 1000","0 <= E <= V*(V-1)/2","Graph is undirected and connected"}'
),
(
  'CodeForge Dijkstra Algorithm',
  'codeforge-dijkstra-algorithm',
  'medium',
  '{"graph","shortest-path","priority-queue"}',
  59.8,
  '{""}',
  'codeforge',
  'Given a weighted graph and a source node, find the shortest distances to all other nodes using Dijkstra algorithm.',
  '[{"input":"graph = [[1,2,4],[0,2,1],[0,1,1,3,5],[2,4]], source = 0","output":"[0,1,2,6,3]","explanation":"Shortest distances from node 0 to all other nodes."}]'::jsonb,
  '{"1 <= V <= 1000","0 <= E <= V*(V-1)/2","Edge weights are non-negative","Graph is connected"}'
),
(
  'CodeForge Bellman Ford Algorithm',
  'codeforge-bellman-ford-algorithm',
  'medium',
  '{"graph","shortest-path"}',
  56.4,
  '{""}',
  'codeforge',
  'Given a weighted graph and a source node, find the shortest distances to all other nodes using Bellman Ford algorithm.',
  '[{"input":"graph = [[1,5],[2,4],[3,2,1,5]], source = 0","output":"[0,5,3,7]","explanation":"Shortest distances from node 0 to all other nodes."}]'::jsonb,
  '{"1 <= V <= 500","0 <= E <= V*(V-1)/2","Edge weights can be negative","No negative cycles"}'
),
(
  'CodeForge Floyd Warshall Algorithm',
  'codeforge-floyd-warshall-algorithm',
  'medium',
  '{"graph","shortest-path","dynamic-programming"}',
  61.2,
  '{""}',
  'codeforge',
  'Given a weighted graph, find the shortest distances between all pairs of vertices using Floyd Warshall algorithm.',
  '[{"input":"graph = [[0,5,INF,10],[INF,0,3,INF],[INF,INF,0,1],[INF,INF,INF,0]]","output":"[[0,5,8,9],[INF,0,3,4],[INF,INF,0,1],[INF,INF,INF,0]]","explanation":"All pairs shortest distances."}]'::jsonb,
  '{"1 <= V <= 500","Edge weights can be negative","No negative cycles"}'
),
(
  'CodeForge Trie Implementation',
  'codeforge-trie-implementation',
  'medium',
  '{"trie","string","design"}',
  64.8,
  '{""}',
  'codeforge',
  'Implement a trie data structure with insert, search, and delete operations.',
  '[{"input":"operations = [\"insert\",\"search\",\"search\",\"startsWith\"], words = [\"apple\",\"apple\",\"app\",\"app\"]","output":"[null,true,true,true]","explanation":"Trie operations demonstration."}]'::jsonb,
  '{"1 <= operations <= 10^4","1 <= word.length <= 100","Words consist of lowercase English letters."}'
),
(
  'CodeForge Segment Tree',
  'codeforge-segment-tree',
  'hard',
  '{"segment-tree","data-structure","range-query"}',
  47.3,
  '{""}',
  'codeforge',
  'Implement a segment tree for range sum queries and point updates.',
  '[{"input":"arr = [1, 3, 5, 7, 9, 11], operations = [\"sum\",\"update\",\"sum\"], values = [[0,2],[2,6],[0,5]]","output":"[9,null,36]","explanation":"Segment tree operations."}]'::jsonb,
  '{"1 <= arr.length <= 10^5","1 <= arr[i] <= 10^9","1 <= operations <= 10^4"}'
),
(
  'CodeForge Fenwick Tree',
  'codeforge-fenwick-tree',
  'medium',
  '{"fenwick-tree","data-structure","range-query"}',
  52.7,
  '{""}',
  'codeforge',
  'Implement a Fenwick tree (Binary Indexed Tree) for point updates and prefix sum queries.',
  '[{"input":"arr = [1, 2, 3, 4, 5], operations = [\"update\",\"query\",\"query\"], values = [[2,6],[1,4],[3,5]]","output":"[null,10,19]","explanation":"Fenwick tree operations."}]'::jsonb,
  '{"1 <= arr.length <= 10^5","1 <= arr[i] <= 10^9","1 <= operations <= 10^4"}'
),
(
  'CodeForge Disjoint Set Union',
  'codeforge-disjoint-set-union',
  'medium',
  '{"union-find","data-structure"}',
  68.9,
  '{""}',
  'codeforge',
  'Implement a Disjoint Set Union (Union Find) data structure with path compression and union by rank.',
  '[{"input":"operations = [\"union\",\"union\",\"find\",\"find\"], values = [[1,2],[2,3],[1,3],[2,3]]","output":"[null,null,true,true]","explanation":"DSU operations demonstration."}]'::jsonb,
  '{"1 <= operations <= 10^4","1 <= element <= 10^5"}'
),
(
  'CodeForge LRU Cache Implementation',
  'codeforge-lru-cache-implementation',
  'medium',
  '{"linked-list","hash-table","design"}',
  58.4,
  '{""}',
  'codeforge',
  'Implement an LRU cache with get and put operations in O(1) time.',
  '[{"input":"operations = [\"put\",\"put\",\"get\",\"put\",\"get\"], values = [[1,1],[2,2],[1],[3,3],[2]]","output":"[null,null,1,null,-1]","explanation":"LRU cache operations."}]'::jsonb,
  '{"1 <= capacity <= 3000","0 <= key <= 3000","0 <= value <= 10^4","1 <= operations <= 10^4"}'
),
(
  'CodeForge Red Black Tree',
  'codeforge-red-black-tree',
  'hard',
  '{"tree","data-structure","balanced-tree"}',
  41.2,
  '{""}',
  'codeforge',
  'Implement a Red Black Tree with insert, delete, and search operations.',
  '[{"input":"operations = [\"insert\",\"insert\",\"search\",\"delete\",\"search\"], values = [10,20,15,10,15]","output":"[null,null,true,null,false]","explanation":"Red Black Tree operations."}]'::jsonb,
  '{"1 <= operations <= 10^4","1 <= value <= 10^9"}'
),
(
  'CodeForge AVL Tree',
  'codeforge-avl-tree',
  'hard',
  '{"tree","data-structure","balanced-tree"}',
  43.8,
  '{""}',
  'codeforge',
  'Implement an AVL tree with insert, delete, and search operations.',
  '[{"input":"operations = [\"insert\",\"insert\",\"search\",\"delete\",\"search\"], values = [10,20,15,10,15]","output":"[null,null,true,null,false]","explanation":"AVL tree operations."}]'::jsonb,
  '{"1 <= operations <= 10^4","1 <= value <= 10^9"}'
),
(
  'CodeForge B Tree',
  'codeforge-b-tree',
  'hard',
  '{"tree","data-structure"}',
  38.7,
  '{""}',
  'codeforge',
  'Implement a B Tree with insert, delete, and search operations.',
  '[{"input":"operations = [\"insert\",\"insert\",\"search\",\"delete\",\"search\"], values = [10,20,15,10,15]","output":"[null,null,true,null,false]","explanation":"B Tree operations."}]'::jsonb,
  '{"1 <= operations <= 10^4","1 <= value <= 10^9","Minimum degree t = 2"}'
)
ON CONFLICT (slug) DO UPDATE SET 
title = EXCLUDED.title,
difficulty = EXCLUDED.difficulty,
tags = EXCLUDED.tags,
acceptance_rate = EXCLUDED.acceptance_rate,
companies = EXCLUDED.companies,
platform = EXCLUDED.platform,
description = EXCLUDED.description,
examples = EXCLUDED.examples,
constraints = EXCLUDED.constraints,
updated_at = NOW();
